import 'package:flutter/material.dart';

/// Global notifier for application language.
/// Defaults to Vietnamese ('vi').
final ValueNotifier<String> languageNotifier = ValueNotifier('vi');

/// Reactive translation system for Swings House.
class AppLocalizations {
  AppLocalizations._();

  static final Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'settings_title': 'Cài đặt hệ thống',
      'nav_home': 'Trang chủ',
      'nav_favorites': 'Yêu thích',
      'nav_post': 'Đăng tin',
      'nav_chat': 'Tin nhắn',
      'nav_profile': 'Cá nhân',
      'leave_draft_title': 'Bỏ thông tin đang nhập?',
      'leave_draft_desc':
          'Bạn đang nhập dở tin đăng. Nếu rời khỏi trang này, thông tin chưa đăng sẽ bị mất.',
      'stay': 'Ở lại',
      'leave_page': 'Rời trang',
      'notifications_off_title': 'Thông báo đang tắt',
      'notifications_off_desc':
          'Bạn có thể bật lại thông báo trong Cài đặt hệ thống để xem các cập nhật mới.',
      'profile_account': 'TÀI KHOẢN',
      'profile_activity': 'HOẠT ĐỘNG',
      'profile_support': 'HỖ TRỢ',
      'profile_personal_info': 'Thông tin cá nhân',
      'profile_change_password': 'Đổi mật khẩu',
      'profile_verify_account': 'Xác thực tài khoản',
      'profile_preferences': 'Nhu cầu tìm phòng',
      'profile_saved_rooms': 'Phòng đã lưu',
      'profile_my_reviews': 'Đánh giá của tôi',
      'profile_search_history': 'Lịch sử tìm kiếm',
      'profile_my_listings': 'Tin đăng của tôi',
      'profile_invoices': 'Hóa đơn & Thanh toán',
      'profile_support_center': 'Trung tâm hỗ trợ',
      'profile_report_issue': 'Báo cáo sự cố',
      'profile_rate_app': 'Đánh giá ứng dụng',
      'profile_about_app': 'Về ứng dụng',
      'profile_logout': 'Đăng xuất',
      'profile_login_now': 'Đăng nhập ngay',
      'profile_register_now': 'Tạo tài khoản mới',
      'profile_not_logged_title': 'Bạn chưa đăng nhập',
      'profile_not_logged_desc':
          'Đăng nhập để quản lý tài khoản, lưu phòng yêu thích và theo dõi tin đăng.',
      'profile_favorites_count': 'Yêu thích',
      'profile_joined_date': 'Ngày tham gia',
      'profile_reviews_count': 'Đánh giá',
      'profile_landlord': 'Chủ nhà',
      'profile_tenant': 'Người thuê',
      'profile_verified': 'Đã xác thực',
      'profile_unverified': 'Chưa xác thực',
      'profile_logout_title': 'Đăng xuất?',
      'profile_logout_desc':
          'Bạn có chắc chắn muốn đăng xuất khỏi tài khoản không?',
      'profile_edit_info': 'Chỉnh sửa thông tin',
      'profile_full_name': 'Họ và tên',
      'profile_phone': 'Số điện thoại',
      'profile_save_changes': 'Lưu thay đổi',
      'profile_name_required': 'Họ và tên không được để trống',
      'profile_update_success': 'Đã cập nhật thông tin thành công',
      'profile_app_rating_thanks': 'Cảm ơn bạn đã đánh giá ứng dụng.',
      'profile_feedback': 'Góp ý',
      'profile_send_rating': 'Gửi đánh giá',
      'profile_update_rating': 'Cập nhật đánh giá',
      'profile_rating_hint':
          'Bạn thích điều gì, hoặc muốn ứng dụng cải thiện điểm nào?',
      'favorites_title': 'Phòng đã lưu',
      'favorites_removed': 'Đã bỏ lưu phòng này',
      'favorites_search_hint': 'Tìm phòng đã lưu...',
      'favorites_sort_newest': 'Mới lưu nhất',
      'favorites_sort_price_asc': 'Giá tăng dần',
      'favorites_sort_price_desc': 'Giá giảm dần',
      'favorites_sort_area': 'Diện tích',
      'favorites_retry': 'Thử lại',
      'favorites_empty_title': 'Chưa có phòng yêu thích',
      'favorites_empty_desc':
          'Lưu những phòng bạn thích để xem lại nhanh tại đây.',
      'favorites_find_now': 'Tìm phòng ngay',
      'favorites_no_result': 'Không tìm thấy',
      'favorites_try_other': 'Thử từ khóa khác nhé',
      'favorites_sort_by': 'Sắp xếp theo',
      'favorites_new_badge': 'MỚI',
      'favorites_saved_time': 'Lưu',
      'favorites_verified': 'Xác thực',
      'favorites_contact': 'Liên hệ',
      'password_current': 'Mật khẩu hiện tại',
      'password_current_hint': 'Nhập mật khẩu hiện tại',
      'password_new': 'Mật khẩu mới',
      'password_new_hint': 'Nhập mật khẩu mới',
      'password_confirm': 'Xác nhận mật khẩu mới',
      'password_confirm_hint': 'Nhập lại mật khẩu mới',
      'password_update': 'Cập nhật mật khẩu',
      'password_success': 'Đổi mật khẩu thành công!',
      'password_weak_warning': 'Mật khẩu mới chưa đạt yêu cầu bảo mật!',
      'password_strength': 'Độ mạnh mật khẩu: ',
      'password_strong': 'Mạnh',
      'password_medium': 'Trung bình',
      'password_weak': 'Yếu',
      'password_empty_strength': 'Chưa nhập',
      'password_min_length': 'Tối thiểu 8 ký tự',
      'password_has_number': 'Chứa ít nhất 1 chữ số (0-9)',
      'password_has_capital': 'Chứa ít nhất 1 chữ cái viết hoa (A-Z)',
      'password_current_required': 'Vui lòng nhập mật khẩu hiện tại',
      'password_new_required': 'Vui lòng nhập mật khẩu mới',
      'password_same_old': 'Mật khẩu mới không được giống mật khẩu cũ',
      'password_confirm_required': 'Vui lòng xác nhận mật khẩu mới',
      'password_confirm_mismatch': 'Mật khẩu xác nhận không trùng khớp',
      'search_history_empty_title': 'Lịch sử trống',
      'search_history_empty_desc':
          'Bạn chưa thực hiện lượt tìm kiếm phòng trọ nào gần đây.',
      'search_history_suggestions': 'Từ khóa gợi ý phổ biến',
      'report_type_account': 'Tài khoản',
      'report_type_listing': 'Tin đăng/phòng trọ',
      'report_type_payment': 'Thanh toán',
      'report_type_chat': 'Nhắn tin/liên hệ',
      'report_type_app': 'Lỗi ứng dụng',
      'report_type_other': 'Khác',
      'report_intro':
          'Hãy mô tả rõ vấn đề bạn gặp phải. SWING HOUSE sẽ dùng thông tin này để kiểm tra và hỗ trợ nhanh hơn.',
      'report_issue_type': 'Loại sự cố',
      'report_content': 'Nội dung báo cáo',
      'report_title_label': 'Tiêu đề',
      'report_title_hint': 'Ví dụ: Không đăng nhập được',
      'report_title_required': 'Vui lòng nhập tiêu đề sự cố',
      'report_desc_label': 'Mô tả chi tiết',
      'report_desc_hint': 'Bạn đang thao tác ở đâu, lỗi hiện ra như thế nào?',
      'report_desc_required': 'Vui lòng mô tả ít nhất 10 ký tự',
      'report_contact_label': 'Email hoặc số điện thoại',
      'report_contact_hint': 'Để đội hỗ trợ liên hệ lại nếu cần',
      'report_device_title': 'Gửi kèm thông tin thiết bị',
      'report_device_desc':
          'Giúp xác định lỗi theo phiên bản app và thiết bị đang dùng.',
      'report_submit': 'Gửi báo cáo',
      'report_success': 'Đã ghi nhận báo cáo sự cố của bạn',
      'yes': 'Có',
      'no': 'Không',
      'support_search_hint': 'Tìm kiếm câu hỏi thường gặp...',
      'support_need_help': 'Bạn vẫn cần trợ giúp?',
      'support_contact_desc':
          'Hãy liên hệ trực tiếp với chúng tôi qua các kênh dưới đây',
      'support_report_bug': 'Báo lỗi',
      'support_no_result': 'Không tìm thấy kết quả',
      'interface_section': 'GIAO DIỆN & CẤU HÌNH',
      'app_theme': 'Giao diện ứng dụng',
      'theme_mode_active': 'Đang áp dụng: ',
      'theme_light': 'Sáng',
      'theme_dark': 'Tối',
      'theme_system': 'Hệ thống',
      'push_notifications': 'Thông báo đẩy',
      'notifications_desc': 'Bật nhận tin nhắn & hóa đơn thanh toán',
      'language': 'Ngôn ngữ',
      'lang_active': 'Đang chọn: ',
      'lang_vi': 'Tiếng Việt',
      'lang_en': 'English',
      'data_section': 'DỌN DẸP DỮ LIỆU',
      'clear_search': 'Xóa lịch sử tìm kiếm',
      'clear_search_desc': 'Xóa danh sách từ khóa tìm kiếm gần đây',
      'clear_cache': 'Dọn dẹp bộ nhớ đệm',
      'clear_cache_desc': 'Giải phóng dữ liệu đệm',
      'account_section': 'TÀI KHOẢN',
      'change_password': 'Thay đổi mật khẩu',
      'change_password_desc': 'Cập nhật mật khẩu đăng nhập của bạn',
      'deactivate_account': 'Vô hiệu hóa tài khoản',
      'deactivate_account_desc': 'Yêu cầu tạm khóa tài khoản của bạn',
      'cancel': 'Hủy',
      'clear': 'Xóa sạch',
      'confirm': 'Đồng ý',
      'clear_search_confirm_title': 'Xóa lịch sử tìm kiếm?',
      'clear_search_confirm_desc':
          'Bạn có chắc chắn muốn xóa toàn bộ lịch sử tìm kiếm gần đây không? Hành động này không thể phục hồi.',
      'clear_search_success': 'Đã xóa lịch sử tìm kiếm thành công',
      'clear_cache_confirm_title': 'Dọn dẹp bộ nhớ đệm?',
      'clear_cache_confirm_desc':
          'Hành động này sẽ xóa các tệp hình ảnh và dữ liệu tạm thời đã lưu để giải phóng không gian bộ nhớ. Các tệp tin gốc không bị ảnh hưởng.',
      'clear_cache_success': 'Đã dọn dẹp bộ nhớ đệm ứng dụng thành công',
      'deactivate_confirm_title': 'CẢNH BÁO: Vô hiệu hóa tài khoản?',
      'deactivate_confirm_desc':
          'Tài khoản của bạn sẽ bị khóa tạm thời. Bạn không thể tìm kiếm, liên hệ hoặc đăng tin phòng trọ. Để kích hoạt lại hoặc xóa vĩnh viễn dữ liệu, bạn cần liên hệ bộ phận hỗ trợ Swings House.',
      'deactivate_confirm_btn': 'Đồng ý vô hiệu hóa',
      'deactivate_success': 'Tài khoản của bạn đã được vô hiệu hóa tạm thời.',
      'lang_changed_snack': 'Đã thay đổi ngôn ngữ sang Tiếng Việt',
      'dialog_clean': 'Dọn dẹp',
    },
    'en': {
      'settings_title': 'System Settings',
      'nav_home': 'Home',
      'nav_favorites': 'Favorites',
      'nav_post': 'Post',
      'nav_chat': 'Messages',
      'nav_profile': 'Profile',
      'leave_draft_title': 'Discard draft?',
      'leave_draft_desc':
          'You are editing a listing draft. If you leave this page, unsaved information will be lost.',
      'stay': 'Stay',
      'leave_page': 'Leave',
      'notifications_off_title': 'Notifications are off',
      'notifications_off_desc':
          'Turn notifications back on in System Settings to see new updates.',
      'profile_account': 'ACCOUNT',
      'profile_activity': 'ACTIVITY',
      'profile_support': 'SUPPORT',
      'profile_personal_info': 'Personal information',
      'profile_change_password': 'Change password',
      'profile_verify_account': 'Account verification',
      'profile_preferences': 'Room preferences',
      'profile_saved_rooms': 'Saved rooms',
      'profile_my_reviews': 'My reviews',
      'profile_search_history': 'Search history',
      'profile_my_listings': 'My listings',
      'profile_invoices': 'Invoices & Payments',
      'profile_support_center': 'Support center',
      'profile_report_issue': 'Report an issue',
      'profile_rate_app': 'Rate app',
      'profile_about_app': 'About app',
      'profile_logout': 'Log out',
      'profile_login_now': 'Log in now',
      'profile_register_now': 'Create new account',
      'profile_not_logged_title': 'You are not logged in',
      'profile_not_logged_desc':
          'Log in to manage your account, save favorite rooms, and track listings.',
      'profile_favorites_count': 'Favorites',
      'profile_joined_date': 'Joined',
      'profile_reviews_count': 'Reviews',
      'profile_landlord': 'Landlord',
      'profile_tenant': 'Tenant',
      'profile_verified': 'Verified',
      'profile_unverified': 'Unverified',
      'profile_logout_title': 'Log out?',
      'profile_logout_desc':
          'Are you sure you want to log out of this account?',
      'profile_edit_info': 'Edit information',
      'profile_full_name': 'Full name',
      'profile_phone': 'Phone number',
      'profile_save_changes': 'Save changes',
      'profile_name_required': 'Full name cannot be empty',
      'profile_update_success': 'Information updated successfully',
      'profile_app_rating_thanks': 'Thank you for rating the app.',
      'profile_feedback': 'Feedback',
      'profile_send_rating': 'Submit rating',
      'profile_update_rating': 'Update rating',
      'profile_rating_hint':
          'What do you like, or what should the app improve?',
      'favorites_title': 'Saved rooms',
      'favorites_removed': 'Removed this room from saved list',
      'favorites_search_hint': 'Search saved rooms...',
      'favorites_sort_newest': 'Newest saved',
      'favorites_sort_price_asc': 'Price low to high',
      'favorites_sort_price_desc': 'Price high to low',
      'favorites_sort_area': 'Area',
      'favorites_retry': 'Retry',
      'favorites_empty_title': 'No saved rooms yet',
      'favorites_empty_desc':
          'Save rooms you like so you can quickly review them here.',
      'favorites_find_now': 'Find rooms now',
      'favorites_no_result': 'No results',
      'favorites_try_other': 'Try another keyword',
      'favorites_sort_by': 'Sort by',
      'favorites_new_badge': 'NEW',
      'favorites_saved_time': 'Saved',
      'favorites_verified': 'Verified',
      'favorites_contact': 'Contact',
      'password_current': 'Current password',
      'password_current_hint': 'Enter current password',
      'password_new': 'New password',
      'password_new_hint': 'Enter new password',
      'password_confirm': 'Confirm new password',
      'password_confirm_hint': 'Re-enter new password',
      'password_update': 'Update password',
      'password_success': 'Password changed successfully!',
      'password_weak_warning':
          'The new password does not meet security requirements!',
      'password_strength': 'Password strength: ',
      'password_strong': 'Strong',
      'password_medium': 'Medium',
      'password_weak': 'Weak',
      'password_empty_strength': 'Not entered',
      'password_min_length': 'At least 8 characters',
      'password_has_number': 'Contains at least 1 number (0-9)',
      'password_has_capital': 'Contains at least 1 uppercase letter (A-Z)',
      'password_current_required': 'Please enter your current password',
      'password_new_required': 'Please enter a new password',
      'password_same_old':
          'New password cannot be the same as the old password',
      'password_confirm_required': 'Please confirm the new password',
      'password_confirm_mismatch': 'Confirmation password does not match',
      'search_history_empty_title': 'No search history',
      'search_history_empty_desc':
          'You have not searched for any rooms recently.',
      'search_history_suggestions': 'Popular suggestions',
      'report_type_account': 'Account',
      'report_type_listing': 'Listing/room',
      'report_type_payment': 'Payment',
      'report_type_chat': 'Messages/contact',
      'report_type_app': 'App error',
      'report_type_other': 'Other',
      'report_intro':
          'Please describe the issue clearly. SWING HOUSE will use this information to investigate and support you faster.',
      'report_issue_type': 'Issue type',
      'report_content': 'Report content',
      'report_title_label': 'Title',
      'report_title_hint': 'Example: Cannot log in',
      'report_title_required': 'Please enter an issue title',
      'report_desc_label': 'Detailed description',
      'report_desc_hint':
          'Where were you using the app, and what error appeared?',
      'report_desc_required': 'Please describe at least 10 characters',
      'report_contact_label': 'Email or phone number',
      'report_contact_hint': 'So support can contact you if needed',
      'report_device_title': 'Include device information',
      'report_device_desc': 'Helps identify issues by app version and device.',
      'report_submit': 'Submit report',
      'report_success': 'Your issue report has been recorded',
      'yes': 'Yes',
      'no': 'No',
      'support_search_hint': 'Search frequently asked questions...',
      'support_need_help': 'Still need help?',
      'support_contact_desc': 'Contact us directly through the channels below',
      'support_report_bug': 'Report bug',
      'support_no_result': 'No results found',
      'interface_section': 'INTERFACE & CONFIGURATION',
      'app_theme': 'App Theme',
      'theme_mode_active': 'Applying: ',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System',
      'push_notifications': 'Push Notifications',
      'notifications_desc': 'Enable messages & payment invoices',
      'language': 'Language',
      'lang_active': 'Selected: ',
      'lang_vi': 'Tiếng Việt',
      'lang_en': 'English',
      'data_section': 'DATA CLEANING',
      'clear_search': 'Clear Search History',
      'clear_search_desc': 'Clear recent search keywords',
      'clear_cache': 'Clear App Cache',
      'clear_cache_desc': 'Free up cache data',
      'account_section': 'ACCOUNT',
      'change_password': 'Change Password',
      'change_password_desc': 'Update your login password',
      'deactivate_account': 'Deactivate Account',
      'deactivate_account_desc': 'Request to temporarily lock account',
      'cancel': 'Cancel',
      'clear': 'Clear',
      'confirm': 'Agree',
      'clear_search_confirm_title': 'Clear search history?',
      'clear_search_confirm_desc':
          'Are you sure you want to clear all recent search history? This action cannot be undone.',
      'clear_search_success': 'Search history cleared successfully',
      'clear_cache_confirm_title': 'Clear app cache?',
      'clear_cache_confirm_desc':
          'This action will clear cached images and temporary files to free up storage space. Original files are not affected.',
      'clear_cache_success': 'App cache cleared successfully',
      'deactivate_confirm_title': 'WARNING: Deactivate Account?',
      'deactivate_confirm_desc':
          'Your account will be temporarily locked. You will not be able to search, contact, or post room listings. To reactivate or permanently delete data, please contact Swings House support.',
      'deactivate_confirm_btn': 'Agree to Deactivate',
      'deactivate_success': 'Your account has been temporarily deactivated.',
      'lang_changed_snack': 'Language changed to English',
      'dialog_clean': 'Clean',
    }
  };

  /// Translate a given key to the currently active language.
  static String tr(String key) {
    final lang = languageNotifier.value;
    return _localizedValues[lang]?[key] ?? key;
  }
}

/// Extension on [String] to make translation clean.
extension TranslationExtension on String {
  String get tr => AppLocalizations.tr(this);
}
