import 'package:flutter/material.dart';

/// Global notifier for application language.
/// Defaults to Vietnamese ('vi').
final ValueNotifier<String> languageNotifier = ValueNotifier('vi');

/// Reactive translation system for Swings House.
class AppLocalizations {
  AppLocalizations._();

  static final Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'settings_title': 'Cài đặt hệ thống',
      'nav_home': 'Trang chủ',
      'nav_favorites': 'Yêu thích',
      'nav_post': 'Đăng tin',
      'nav_chat': 'Tin nhắn',
      'nav_profile': 'Cá nhân',
      'leave_draft_title': 'Bỏ thông tin đang nhập?',
      'leave_draft_desc':
          'Bạn đang nhập dở tin đăng. Nếu rời khỏi trang này, thông tin chưa đăng sẽ bị mất.',
      'stay': 'Ở lại',
      'leave_page': 'Rời trang',
      'notifications_off_title': 'Thông báo đang tắt',
      'notifications_off_desc':
          'Bạn có thể bật lại thông báo trong Cài đặt hệ thống để xem các cập nhật mới.',
      'profile_account': 'TÀI KHOẢN',
      'profile_activity': 'HOẠT ĐỘNG',
      'profile_support': 'HỖ TRỢ',
      'profile_personal_info': 'Thông tin cá nhân',
      'profile_change_password': 'Đổi mật khẩu',
      'profile_verify_account': 'Xác thực tài khoản',
      'profile_preferences': 'Nhu cầu tìm phòng',
      'profile_saved_rooms': 'Phòng đã lưu',
      'profile_my_reviews': 'Đánh giá của tôi',
      'profile_search_history': 'Lịch sử tìm kiếm',
      'profile_my_listings': 'Tin đăng của tôi',
      'profile_invoices': 'Hóa đơn & Thanh toán',
      'profile_support_center': 'Trung tâm hỗ trợ',
      'profile_report_issue': 'Báo cáo sự cố',
      'profile_rate_app': 'Đánh giá ứng dụng',
      'profile_about_app': 'Về ứng dụng',
      'profile_logout': 'Đăng xuất',
      'profile_login_now': 'Đăng nhập ngay',
      'profile_register_now': 'Tạo tài khoản mới',
      'profile_not_logged_title': 'Bạn chưa đăng nhập',
      'profile_not_logged_desc':
          'Đăng nhập để quản lý tài khoản, lưu phòng yêu thích và theo dõi tin đăng.',
      'profile_favorites_count': 'Yêu thích',
      'profile_joined_date': 'Ngày tham gia',
      'profile_reviews_count': 'Đánh giá',
      'profile_landlord': 'Chủ nhà',
      'profile_tenant': 'Người thuê',
      'profile_verified': 'Đã xác thực',
      'profile_unverified': 'Chưa xác thực',
      'profile_logout_title': 'Đăng xuất?',
      'profile_logout_desc':
          'Bạn có chắc chắn muốn đăng xuất khỏi tài khoản không?',
      'profile_edit_info': 'Chỉnh sửa thông tin',
      'profile_full_name': 'Họ và tên',
      'profile_phone': 'Số điện thoại',
      'profile_save_changes': 'Lưu thay đổi',
      'profile_name_required': 'Họ và tên không được để trống',
      'profile_update_success': 'Đã cập nhật thông tin thành công',
      'profile_app_rating_thanks': 'Cảm ơn bạn đã đánh giá ứng dụng.',
      'profile_feedback': 'Góp ý',
      'profile_send_rating': 'Gửi đánh giá',
      'profile_update_rating': 'Cập nhật đánh giá',
      'profile_rating_hint':
          'Bạn thích điều gì, hoặc muốn ứng dụng cải thiện điểm nào?',
      'favorites_title': 'Phòng đã lưu',
      'favorites_removed': 'Đã bỏ lưu phòng này',
      'favorites_search_hint': 'Tìm phòng đã lưu...',
      'favorites_sort_newest': 'Mới lưu nhất',
      'favorites_sort_price_asc': 'Giá tăng dần',
      'favorites_sort_price_desc': 'Giá giảm dần',
      'favorites_sort_area': 'Diện tích',
      'favorites_retry': 'Thử lại',
      'favorites_empty_title': 'Chưa có phòng yêu thích',
      'favorites_empty_desc':
          'Lưu những phòng bạn thích để xem lại nhanh tại đây.',
      'favorites_find_now': 'Tìm phòng ngay',
      'favorites_no_result': 'Không tìm thấy',
      'favorites_try_other': 'Thử từ khóa khác nhé',
      'favorites_sort_by': 'Sắp xếp theo',
      'favorites_new_badge': 'MỚI',
      'favorites_saved_time': 'Lưu',
      'favorites_verified': 'Xác thực',
      'favorites_contact': 'Liên hệ',
      'favorites_undo': 'Hoàn tác',
      'favorites_month_suffix': '/tháng',
      'favorites_load_error': 'Không tải được danh sách yêu thích',
      'favorites_retry_desc': 'Vui lòng thử lại.',
      'today': 'Hôm nay',
      'yesterday': 'Hôm qua',
      'days_ago': '{days} ngày trước',
      'password_current': 'Mật khẩu hiện tại',
      'password_current_hint': 'Nhập mật khẩu hiện tại',
      'password_new': 'Mật khẩu mới',
      'password_new_hint': 'Nhập mật khẩu mới',
      'password_confirm': 'Xác nhận mật khẩu mới',
      'password_confirm_hint': 'Nhập lại mật khẩu mới',
      'password_update': 'Cập nhật mật khẩu',
      'password_success': 'Đổi mật khẩu thành công!',
      'password_weak_warning': 'Mật khẩu mới chưa đạt yêu cầu bảo mật!',
      'password_strength': 'Độ mạnh mật khẩu: ',
      'password_strong': 'Mạnh',
      'password_medium': 'Trung bình',
      'password_weak': 'Yếu',
      'password_empty_strength': 'Chưa nhập',
      'password_min_length': 'Tối thiểu 8 ký tự',
      'password_has_number': 'Chứa ít nhất 1 chữ số (0-9)',
      'password_has_capital': 'Chứa ít nhất 1 chữ cái viết hoa (A-Z)',
      'password_current_required': 'Vui lòng nhập mật khẩu hiện tại',
      'password_new_required': 'Vui lòng nhập mật khẩu mới',
      'password_same_old': 'Mật khẩu mới không được giống mật khẩu cũ',
      'password_confirm_required': 'Vui lòng xác nhận mật khẩu mới',
      'password_confirm_mismatch': 'Mật khẩu xác nhận không trùng khớp',
      'verify_gateways_title': 'Các cổng liên kết bảo mật',
      'verify_email': 'Xác minh Email',
      'verify_email_unlinked': 'Chưa liên kết Email',
      'verify_email_verified': 'Đã xác minh',
      'verify_email_verify_now': 'Xác minh ngay',
      'verify_phone': 'Số điện thoại',
      'verify_phone_unverified': 'Chưa xác thực số điện thoại',
      'verify_phone_verified': 'Đã xác thực',
      'verify_phone_verify_now': 'Xác thực ngay',
      'verify_google': 'Tài khoản Google',
      'verify_google_desc': 'Liên kết tài khoản Google để đăng nhập nhanh',
      'verify_facebook': 'Tài khoản Facebook',
      'verify_facebook_desc': 'Liên kết tài khoản Facebook để bảo mật',
      'verify_action_link': 'Liên kết',
      'verify_action_unlink': 'Hủy liên kết',
      'verify_trust_title': 'Độ tin cậy tài khoản',
      'verify_trust_level_label': 'Mức độ: {level}',
      'verify_trust_level_absolute': 'Tuyệt đối',
      'verify_trust_level_high': 'Rất cao',
      'verify_trust_level_medium': 'Trung bình',
      'verify_trust_level_low': 'Thấp',
      'verify_trust_success_desc':
          'Tuyệt vời! Tài khoản của bạn đã đạt mức độ tin cậy tuyệt đối và kích hoạt Huy hiệu Xác thực xanh.',
      'verify_trust_warning_desc':
          'Hãy xác thực thêm số điện thoại và liên kết các mạng xã hội để đạt mức độ tin cậy 100%!',
      'verify_security_commitment':
          'Swings House cam kết bảo mật 100% dữ liệu liên kết tài khoản của bạn. Việc liên kết này chỉ dùng để tăng tính tin cậy của thông tin hiển thị trên tin đăng trọ của bạn.',
      'verify_confirm_unlink_google_title': 'Hủy liên kết Google',
      'verify_confirm_unlink_google_desc':
          'Bạn có chắc chắn muốn hủy liên kết tài khoản Google này không?',
      'verify_confirm_unlink_facebook_title': 'Hủy liên kết Facebook',
      'verify_confirm_unlink_facebook_desc':
          'Bạn có chắc chắn muốn hủy liên kết tài khoản Facebook này không?',
      'verify_success_google_link': 'Liên kết tài khoản Google thành công!',
      'verify_success_facebook_link': 'Liên kết tài khoản Facebook thành công!',
      'verify_success_phone_verify': 'Xác thực số điện thoại thành công!',
      'verify_email_sent_mock':
          'Yêu cầu xác minh đã gửi! Đã tự động mô phỏng xác minh Email thành công.',
      'verify_dialog_cancel': 'Hủy',
      'verify_otp_title': 'Nhập mã xác thực OTP',
      'verify_otp_sent_to': 'Mã OTP đã được gửi đến số {phone}',
      'verify_otp_instruction':
          'Swings House sẽ gửi một mã OTP 6 chữ số đến số điện thoại này.',
      'verify_phone_input_hint': 'Nhập số điện thoại của bạn',
      'verify_otp_get_code': 'Nhận mã OTP',
      'verify_otp_resend_countdown': 'Gửi lại mã sau {seconds}s',
      'verify_otp_not_received': 'Không nhận được mã? ',
      'verify_otp_resend_now': 'Gửi lại ngay',
      'verify_otp_confirm': 'Xác nhận',
      'verify_otp_invalid_phone': 'Vui lòng nhập số điện thoại hợp lệ!',
      'verify_otp_invalid_otp': 'Vui lòng nhập đủ mã OTP 6 số!',
      'verify_email_input_hint': 'Nhập địa chỉ email của bạn',
      'verify_otp_sent_to_email': 'Mã OTP đã được gửi đến email {email}',
      'verify_otp_instruction_email':
          'Swings House sẽ gửi mã OTP gồm 6 chữ số đến email này.',
      'verify_otp_invalid_email': 'Vui lòng nhập địa chỉ email hợp lệ!',
      'verify_success_email_verify': 'Xác thực địa chỉ email thành công!',
      'search_history_empty_title': 'Lịch sử trống',
      'search_history_empty_desc':
          'Bạn chưa thực hiện lượt tìm kiếm phòng trọ nào gần đây.',
      'search_history_suggestions': 'Từ khóa gợi ý phổ biến',
      'report_type_account': 'Tài khoản',
      'report_type_listing': 'Tin đăng/phòng trọ',
      'report_type_payment': 'Thanh toán',
      'report_type_chat': 'Nhắn tin/liên hệ',
      'report_type_app': 'Lỗi ứng dụng',
      'report_type_other': 'Khác',
      'report_intro':
          'Hãy mô tả rõ vấn đề bạn gặp phải. SWING HOUSE sẽ dùng thông tin này để kiểm tra và hỗ trợ nhanh hơn.',
      'report_issue_type': 'Loại sự cố',
      'report_content': 'Nội dung báo cáo',
      'report_title_label': 'Tiêu đề',
      'report_title_hint': 'Ví dụ: Không đăng nhập được',
      'report_title_required': 'Vui lòng nhập tiêu đề sự cố',
      'report_desc_label': 'Mô tả chi tiết',
      'report_desc_hint': 'Bạn đang thao tác ở đâu, lỗi hiện ra như thế nào?',
      'report_desc_required': 'Vui lòng mô tả ít nhất 10 ký tự',
      'report_contact_label': 'Email hoặc số điện thoại',
      'report_contact_hint': 'Để đội hỗ trợ liên hệ lại nếu cần',
      'report_device_title': 'Gửi kèm thông tin thiết bị',
      'report_device_desc':
          'Giúp xác định lỗi theo phiên bản app và thiết bị đang dùng.',
      'report_submit': 'Gửi báo cáo',
      'report_success': 'Đã ghi nhận báo cáo sự cố của bạn',
      'yes': 'Có',
      'no': 'Không',
      'support_search_hint': 'Tìm kiếm câu hỏi thường gặp...',
      'support_need_help': 'Bạn vẫn cần trợ giúp?',
      'support_contact_desc':
          'Hãy liên hệ trực tiếp với chúng tôi qua các kênh dưới đây',
      'support_report_bug': 'Báo lỗi',
      'support_no_result': 'Không tìm thấy kết quả',
      'interface_section': 'GIAO DIỆN & CẤU HÌNH',
      'app_theme': 'Giao diện ứng dụng',
      'theme_mode_active': 'Đang áp dụng: ',
      'theme_light': 'Sáng',
      'theme_dark': 'Tối',
      'theme_system': 'Hệ thống',
      'push_notifications': 'Thông báo đẩy',
      'notifications_desc': 'Bật nhận tin nhắn & hóa đơn thanh toán',
      'language': 'Ngôn ngữ',
      'lang_active': 'Đang chọn: ',
      'lang_vi': 'Tiếng Việt',
      'lang_en': 'English',
      'data_section': 'DỌN DẸP DỮ LIỆU',
      'clear_search': 'Xóa lịch sử tìm kiếm',
      'clear_search_desc': 'Xóa danh sách từ khóa tìm kiếm gần đây',
      'clear_cache': 'Dọn dẹp bộ nhớ đệm',
      'clear_cache_desc': 'Giải phóng dữ liệu đệm',
      'account_section': 'TÀI KHOẢN',
      'change_password': 'Thay đổi mật khẩu',
      'change_password_desc': 'Cập nhật mật khẩu đăng nhập của bạn',
      'deactivate_account': 'Vô hiệu hóa tài khoản',
      'deactivate_account_desc': 'Yêu cầu tạm khóa tài khoản của bạn',
      'cancel': 'Hủy',
      'clear': 'Xóa sạch',
      'confirm': 'Đồng ý',
      'clear_search_confirm_title': 'Xóa lịch sử tìm kiếm?',
      'clear_search_confirm_desc':
          'Bạn có chắc chắn muốn xóa toàn bộ lịch sử tìm kiếm gần đây không? Hành động này không thể phục hồi.',
      'clear_search_success': 'Đã xóa lịch sử tìm kiếm thành công',
      'clear_cache_confirm_title': 'Dọn dẹp bộ nhớ đệm?',
      'clear_cache_confirm_desc':
          'Hành động này sẽ xóa các tệp hình ảnh và dữ liệu tạm thời đã lưu để giải phóng không gian bộ nhớ. Các tệp tin gốc không bị ảnh hưởng.',
      'clear_cache_success': 'Đã dọn dẹp bộ nhớ đệm ứng dụng thành công',
      'deactivate_confirm_title': 'CẢNH BÁO: Vô hiệu hóa tài khoản?',
      'deactivate_confirm_desc':
          'Tài khoản của bạn sẽ bị khóa tạm thời. Bạn không thể tìm kiếm, liên hệ hoặc đăng tin phòng trọ. Để kích hoạt lại hoặc xóa vĩnh viễn dữ liệu, bạn cần liên hệ bộ phận hỗ trợ Swings House.',
      'deactivate_confirm_btn': 'Đồng ý vô hiệu hóa',
      'deactivate_success': 'Tài khoản của bạn đã được vô hiệu hóa tạm thời.',
      'dialog_clean': 'Dọn dẹp',
      // Home & Filter
      'home_hello': 'Xin chào 👋',
      'home_welcome_question': 'Bạn muốn tìm phòng nào?',
      'home_search_hint': 'Tìm kiếm phòng, khu vực...',
      'home_category_all': 'Tất cả',
      'home_filter_title': 'Bộ lọc tìm kiếm',
      'home_filter_reset': 'Đặt lại',
      'home_filter_apply': 'Áp dụng',
      'home_filter_type': 'Loại hình',
      'home_filter_price': 'Khoảng giá (triệu/tháng)',
      'home_filter_price_unlimited': 'Không giới hạn',
      'home_filter_area': 'Diện tích (m²)',
      'home_filter_amenity': 'Tiện ích phòng',
      'home_filter_gender': 'Giới hạn giới tính',
      'home_filter_gender_all': 'Tất cả giới tính',
      'home_filter_gender_male': 'Chỉ nam',
      'home_filter_gender_female': 'Chỉ nữ',
      'home_filter_gender_none': 'Không giới hạn',
      'home_no_listings': 'Không tìm thấy tin đăng nào phù hợp',
      'home_load_more': 'Tải thêm',
      'home_location_picker': 'Chọn vị trí',
      'home_type_phong_tro': 'Phòng trọ SV',
      'home_type_can_ho': 'Căn hộ DV',
      'home_type_o_ghep': 'Ở ghép',
      'home_type_nha_can': 'Nhà nguyên căn',
      'home_categories_title': 'Loại hình',
      'home_type_phong_tro_short': 'Phòng trọ\nSV',
      'home_type_can_ho_short': 'Căn hộ\nDV',
      'home_type_o_ghep_short': 'Ở ghép',
      'home_type_nha_can_short': 'Nhà\nnguyên căn',
      'home_price_unit_short': '/th',
      'home_price_unit_long': '/tháng',
      'home_filter_nearby': 'Gần đây',
      'home_filter_by_budget': 'Theo ngân sách',
      'home_filter_new': 'Phòng mới',
      'home_filter_allow_pet': 'Nuôi thú cưng',
      'home_filter_vip': 'VIP',
      'home_location_all': 'Tất cả khu vực',
      'home_location_select_title': 'Chọn khu vực',
      'home_filter_active_banner': 'Đang áp dụng bộ lọc',
      'home_filter_clear': 'Xóa lọc',
      'home_pref_banner_prefix': 'Ưu tiên: {preferences}',
      'home_pref_banner_empty':
          'Gợi ý đang được cá nhân hóa theo khảo sát của bạn',
      'home_pref_banner_edit': 'Sửa',
      'home_pref_budget_under': 'Dưới {budget}tr',
      'home_sql_fallback': 'Chưa kết nối được SQL, đang hiển thị dữ liệu mẫu.',
      'home_featured_empty': 'Không có tin nổi bật phù hợp',
      'home_featured_title': '⭐  Tin nổi bật',
      'home_suggested_title': '🎯  Gợi ý cho bạn',
      'home_view_more': 'Xem thêm',
      'home_view_all': 'Xem tất cả',
      'home_search_results_count': '{count} kết quả cho "{query}"',
      'home_search_empty_title': 'Không tìm thấy kết quả',
      'home_search_empty_desc':
          'Thử tìm với từ khóa khác\nhoặc điều chỉnh bộ lọc',
      'home_status_rented': 'Đã thuê',
      'home_status_hot': '🔥 Hot',
      'home_status_available': 'Còn phòng',
      'home_badge_featured': 'NỔI BẬT',
      'home_badge_new': 'MỚI',
      'home_banner_fallback_title': 'Phòng VIP giá tốt',
      'home_banner_fallback_subtitle': 'Xác thực · Ảnh thực tế · An toàn',
      // Amenities
      'Wifi': 'Wifi',
      'Điều hòa': 'Điều hòa',
      'Thang máy': 'Thang máy',
      'Máy giặt': 'Máy giặt',
      'Ban công': 'Ban công',
      'Bảo vệ': 'Bảo vệ',
      'Sân vườn': 'Sân vườn',
      'Nuôi thú': 'Nuôi thú',
      // Notifications
      'notif_title': 'Thông báo',
      'notif_unread_suffix': 'chưa đọc',
      'notif_empty': 'Chưa có thông báo',
      'notif_empty_desc':
          'Các cập nhật về tin đăng, tin nhắn và thanh toán sẽ hiển thị tại đây.',
      'notif_load_failed': 'Không tải được thông báo',
      'notif_retry': 'Thử lại',
      'notif_just_now': 'Vừa xong',
      'notif_mins_ago': 'phút trước',
      'notif_hours_ago': 'giờ trước',
      'notif_days_ago': 'ngày trước',
      // Listing Create
      'post_step_title_1': 'Loại hình & Tiêu đề',
      'post_step_title_2': 'Ảnh phòng (6 ảnh)',
      'post_step_title_3': 'Địa chỉ',
      'post_step_title_4': 'Chi tiết phòng',
      'post_step_title_5': 'Giá & Tiện ích',
      'post_success': 'Đăng tin thành công! Đang chờ xét duyệt.',
      'post_failed': 'Đăng tin thất bại',
      'post_header_title': 'Đăng tin',
      'post_header_edit_title': 'Sửa tin đăng',
      'post_header_step': 'Bước {step}/{total} · {title}',
      'post_img_cover': 'Ảnh bìa',
      'post_img_extra': 'Ảnh phụ',
      'post_img_add': 'Thêm ảnh',
      'post_video_add': 'Thêm video',
      'post_video_limit': 'Tối đa',
      'post_validation_type': 'Vui lòng chọn loại hình phòng.',
      'post_validation_title': 'Vui lòng nhập tiêu đề tin đăng.',
      'post_validation_cover':
          'Vui lòng thêm ảnh bìa để admin có thể duyệt tin.',
      'post_validation_province': 'Vui lòng chọn tỉnh / thành phố.',
      'post_validation_district': 'Vui lòng chọn quận / huyện.',
      'post_validation_ward': 'Vui lòng chọn phường / xã.',
      'post_validation_street': 'Vui lòng nhập địa chỉ chi tiết.',
      'post_validation_area': 'Vui lòng nhập diện tích hợp lệ.',
      'post_validation_occupants': 'Vui lòng nhập số người tối đa hợp lệ.',
      'post_validation_price': 'Vui lòng nhập giá thuê hợp lệ.',
      'post_validation_image_limit':
          'Gói đã chọn chỉ cho phép tối đa {max} ảnh.',
      'post_validation_video_limit':
          'Gói đã chọn chỉ cho phép tối đa {max} video.',
      'post_discard_draft_title': 'Bỏ thông tin đang nhập?',
      'post_discard_draft_desc':
          'Bạn đang nhập dở tin đăng. Nếu rời khỏi trang này, thông tin chưa đăng sẽ bị mất.',
      'post_draft_stay': 'Ở lại',
      'post_draft_leave': 'Rời trang',
      'post_btn_prev': 'Quay lại',
      'post_btn_next': 'Tiếp tục',
      'post_btn_submit': 'Đăng tin ngay',
      'post_title': 'Đăng tin cho thuê',
      'post_step_prefix': 'Bước',
      'post_help': 'Trợ giúp',
      'post_help_sheet_title': 'Trợ giúp đăng tin',
      'post_help_sheet_subtitle': 'Mẹo cho bước: {title}',
      'post_help_open_support': 'Trung tâm hỗ trợ',
      'post_help_report_issue': 'Báo lỗi',
      'post_help_step1_tip1':
          'Chọn đúng loại hình để người thuê lọc và tìm thấy tin nhanh hơn.',
      'post_help_step1_tip2':
          'Tiêu đề nên nêu rõ khu vực, điểm mạnh và mức giá nổi bật.',
      'post_help_step1_tip3':
          'Mô tả càng cụ thể về nội thất, giờ giấc và chi phí thì càng giảm câu hỏi lặp lại.',
      'post_help_step2_tip1':
          'Ảnh bìa nên sáng, rõ, chụp góc rộng và thể hiện không gian chính.',
      'post_help_step2_tip2':
          'Thêm ảnh nhà vệ sinh, khu bếp, chỗ để xe và lối vào để tăng độ tin cậy.',
      'post_help_step2_tip3':
          'Video chỉ khả dụng với gói hỗ trợ video; nếu không thấy ô video hãy kiểm tra gói đang chọn.',
      'post_help_step3_tip1':
          'Nhập địa chỉ càng đầy đủ thì bản đồ và tìm kiếm khu vực càng chính xác.',
      'post_help_step3_tip2':
          'Nếu bản đồ không tự nhận diện, bạn vẫn có thể chọn vị trí thủ công trên bản đồ.',
      'post_help_step3_tip3':
          'Không nên ghi số phòng riêng tư trong mô tả công khai nếu chưa cần thiết.',
      'post_help_step4_tip1':
          'Diện tích, số người tối đa và tầng nên đúng thực tế để tránh khiếu nại.',
      'post_help_step4_tip2':
          'Ngày có thể vào ở giúp người thuê biết tin còn phù hợp hay không.',
      'post_help_step4_tip3':
          'Chính sách thú cưng cần ghi rõ ngay từ đầu nếu chủ nhà có giới hạn.',
      'post_help_step5_tip1':
          'Giá thuê nhập theo VND mỗi tháng, không dùng dấu chấm hoặc chữ trong ô giá.',
      'post_help_step5_tip2':
          'Điền điện, nước, internet và gửi xe để người thuê ước tính tổng chi phí.',
      'post_help_step5_tip3':
          'Chọn đúng tiện ích để tin xuất hiện trong bộ lọc tìm kiếm liên quan.',
      'post_label_type': 'Loại hình',
      'post_label_photos': 'Ảnh',
      'post_label_address': 'Địa chỉ',
      'post_label_details': 'Chi tiết',
      'post_label_pricing': 'Giá cả',
      'post_room_type_section': 'Loại hình phòng',
      'post_basic_info_section': 'Thông tin cơ bản',
      'post_title_label': 'Tiêu đề tin đăng',
      'post_title_hint': 'VD: Phòng trọ full nội thất Bình Thạnh giá rẻ',
      'post_desc_label': 'Mô tả chi tiết',
      'post_desc_hint': 'Mô tả đặc điểm nổi bật, tiện ích xung quanh...',
      'post_package_section': 'Gói đăng tin',
      'post_package_loading': 'Đang tải các gói...',
      'post_package_error': 'Lỗi tải gói đăng tin',
      'post_package_reload': 'Tải lại gói',
      'post_img_banner_title': 'Ảnh phòng - tối đa {max} ảnh',
      'post_img_banner_desc':
          '- Gói {package} cho phép {max} ảnh trong bản hiện tại\n- Ảnh đầu tiên là ảnh bìa hiển thị trên danh sách\n- Định dạng JPG/PNG, tối đa 5 MB mỗi ảnh',
      'post_img_list_title': 'Danh sách ảnh',
      'post_img_count': '{current} / {max} ảnh',
      'post_img_add_cover': 'Thêm ảnh bìa',
      'post_img_add_extra': 'Ảnh {index}',
      'post_img_click_gallery': 'Nhấn để chọn từ thư viện',
      'post_img_tip':
          'Mẹo: Ảnh sáng, rõ nét, chụp từ nhiều góc giúp tăng 3x lượt liên hệ!',
      'post_video_not_supported': 'Gói hiện tại không hỗ trợ video.',
      'post_video_section': 'Video phòng',
      'post_video_list': 'Danh sách video',
      'post_video_count': '{current} / {max} video',
      'post_video_hint': 'Chọn video {index}',
      'post_video_specs': 'Hỗ trợ MP4/MOV/WebM, tối đa 100 MB mỗi video.',
      'post_address_section': 'Địa chỉ phòng',
      'post_select_field': 'Chọn {field}',
      'post_province_label': 'Tỉnh / Thành phố',
      'post_district_label': 'Quận / Huyện',
      'post_ward_label': 'Phường / Xã',
      'post_street_label': 'Địa chỉ chi tiết',
      'post_street_hint': 'Số nhà, tên đường...',
      'post_map_resolving': 'Đang tự điền địa chỉ...',
      'post_map_select_hint': 'Chạm để chọn vị trí trên bản đồ',
      'post_map_tap_instruction': 'Chạm vào bản đồ để đặt vị trí',
      'post_map_selected_pos': 'Vị trí đã chọn',
      'post_map_use_pos': 'Dùng vị trí này',
      'post_map_no_service': 'Vui lòng bật dịch vụ vị trí trên thiết bị.',
      'post_map_no_permission': 'Ứng dụng chưa được cấp quyền vị trí.',
      'post_map_err_get_pos': 'Không lấy được vị trí hiện tại.',
      'post_map_search_hint': 'Tìm địa chỉ trên OpenStreetMap',
      'post_map_search_empty': 'Không tìm thấy địa chỉ phù hợp.',
      'post_map_search_error': 'Không tìm được địa chỉ. Vui lòng thử lại.',
      'post_details_area_section': 'Diện tích & Tầng',
      'post_details_area_label': 'Diện tích (m2)',
      'post_details_occupants_label': 'Số người tối đa',
      'post_details_occupants_unit': 'người',
      'post_details_floor_label': 'Tầng',
      'post_details_floor_unit': 'tầng',
      'post_details_total_floors_label': 'Tổng số tầng',
      'post_details_available_section': 'Ngày có thể vào ở',
      'post_details_available_hint': 'Chọn ngày có thể vào ở',
      'post_details_date_format': 'Ngày {day}/{month}/{year}',
      'post_policy_section': 'Chính sách',
      'post_policy_pet_title': 'Cho phép nuôi thú cưng',
      'post_policy_pet_desc': 'Chó, mèo, thú nhỏ...',
      'post_price_section': 'Giá thuê',
      'post_price_label': 'Giá thuê mỗi tháng (VND)',
      'post_price_unit': 'đ/tháng',
      'post_services_section': 'Chi phí dịch vụ',
      'post_service_electric': 'Điện (đ/kWh)',
      'post_service_water': 'Nước (đ/m3)',
      'post_service_internet': 'Internet (đ/tháng)',
      'post_service_parking': 'Gửi xe (đ/tháng)',
      'post_amenities_section': 'Tiện ích đi kèm',
      'post_amenities_empty': 'Không có tiện ích nào khả dụng.',
      'post_preview_title': 'Xem trước tin đăng',
      'post_preview_no_title': 'Tiêu đề chưa nhập',
      'post_preview_no_type': 'Chưa chọn loại hình',
      'post_preview_no_price': '---',
      'post_preview_no_address': 'Chưa nhập địa chỉ',
      'post_preview_images': '{count} ảnh',
      'post_preview_videos': '{count} video',
      'post_submitting': 'Đang đăng tin...',
      'post_img_slot_cover': 'Slot 1 (Ảnh bìa)',
      'post_img_slot_index': 'Slot {index}',
      'post_tooltip_make_cover': 'Đặt làm ảnh bìa',
      'post_tooltip_change_img': 'Thay ảnh',
      'post_tooltip_delete': 'Xoá',
      'post_video_none': 'Không video',
      'post_package_desc': '{photos} ảnh • {videos} • {days} ngày',
      'post_img_limit_reached': 'Gói {package} chỉ cho phép tối đa {max} ảnh.',
      'post_package_current': 'gói hiện tại',
      'post_address_resolve_error':
          'Đã chọn tọa độ, nhưng chưa tự nhận diện được địa chỉ.',
      'post_img_upload_timeout':
          'Tin đã được tạo, nhưng upload ảnh quá lâu. Bạn vẫn có thể mua gói VIP.',
      'post_img_upload_failed':
          'Tin đã được tạo, nhưng chưa cập nhật được ảnh. Bạn vẫn có thể mua gói VIP.',
      'post_video_upload_timeout':
          'Tin đã được tạo, nhưng upload video quá lâu. Bạn có thể bổ sung video sau.',
      'post_video_upload_failed':
          'Tin đã được tạo, nhưng chưa upload được video.',
      'post_area_unit': 'm²',
      'invoice_load_failed': 'Không tải được hóa đơn',
      'invoice_retry': 'Thử lại',
      'invoice_empty_title': 'Chưa có hóa đơn',
      'invoice_empty_desc': 'Các hóa đơn mua gói đăng tin sẽ hiển thị tại đây.',
      'invoice_view_packages': 'Xem gói đăng tin',
      'invoice_summary_total': 'Tổng',
      'invoice_summary_paid': 'Đã thanh toán',
      'invoice_summary_pending': 'Chờ xử lý',
      'invoice_card_code': 'Mã hóa đơn',
      'invoice_card_type': 'Loại hóa đơn',
      'invoice_card_amount': 'Số tiền',
      'invoice_card_created': 'Ngày tạo',
      'invoice_card_note': 'Ghi chú',
      'invoice_btn_view_listing': 'Xem tin',
      'invoice_btn_pay': 'Thanh toán',
      'invoice_btn_processing': 'Đang xử lý',
      'invoice_btn_view_bill': 'Xem bill',
      'invoice_status_paid': 'Đã thanh toán',
      'invoice_status_pending': 'Chờ thanh toán',
      'invoice_status_failed': 'Thất bại',
      'invoice_status_refund': 'Hoàn tiền',
      'invoice_status_unknown': 'Trạng thái #{id}',
      'invoice_type_post_package': 'Gói đăng tin',
      'invoice_pay_success':
          'Thanh toán thành công. Gói VIP đã được kích hoạt.',
      'invoice_bill_title': 'SWING HOUSE - BILL THANH TOÁN',
      'invoice_bill_code': 'Mã hóa đơn: {code}',
      'invoice_bill_type': 'Loại hóa đơn: {type}',
      'invoice_bill_status': 'Trạng thái: {status}',
      'invoice_bill_amount': 'Số tiền: {amount}',
      'invoice_bill_created': 'Ngày tạo: {date}',
      'invoice_bill_due': 'Hạn thanh toán: {date}',
      'invoice_bill_listing': 'Mã tin đăng: #{id}',
      'invoice_bill_note': 'Ghi chú: {note}',
      'invoice_bill_thank_you': 'Cảm ơn bạn đã sử dụng SWING HOUSE.',
      'invoice_bill_total_payment': 'Tổng thanh toán',
      'invoice_btn_copy': 'Sao chép',
      'invoice_btn_export': 'Xuất file',
      'invoice_btn_view_related_listing': 'Xem tin đăng liên quan',
      'invoice_export_success':
          'Đã xuất bill và sao chép nội dung. File: {path}',
      'invoice_export_failed': 'Không thể xuất bill: {error}',
      'invoice_copy_success': 'Đã sao chép nội dung bill.',
      'invoice_bill_due_label': 'Hạn thanh toán',
      'invoice_bill_listing_label': 'Mã tin đăng',
      'post_package_must_post_first': 'Hãy đăng tin trước khi mua gói VIP.',
      'invoice_dialog_created_title': 'Đã tạo hóa đơn',
      'invoice_dialog_code': 'Mã hóa đơn: {code}',
      'invoice_dialog_amount': 'Số tiền: {amount}',
      'invoice_dialog_success_desc':
          'Sau khi thanh toán thành công, gói {package} sẽ được kích hoạt cho tin đăng.',
      'invoice_dialog_btn_later': 'Thanh toán sau',
      'invoice_dialog_btn_simulate': 'Mô phỏng đã thanh toán',
      'invoice_pay_now': 'Thanh toán PayOS',
      'invoice_qr_title': 'Quét mã QR PayOS',
      'invoice_qr_desc':
          'Dùng ứng dụng ngân hàng để quét mã và hoàn tất thanh toán.',
      'invoice_qr_unavailable':
          'Hóa đơn này chưa có mã QR. Hãy mở trang PayOS để thanh toán.',
      'invoice_open_checkout': 'Mở trang PayOS',
      'invoice_open_checkout_failed': 'Không mở được trang thanh toán PayOS.',
      'invoice_payment_link_missing':
          'Hóa đơn này chưa có link thanh toán PayOS.',
      'invoice_checking_payment': 'Đang kiểm tra thanh toán...',
      'invoice_waiting_payment':
          'Sau khi thanh toán, màn hình sẽ tự chuyển trạng thái.',
      'invoice_sync_payment_failed':
          'Chưa kiểm tra được trạng thái thanh toán. Vui lòng chờ hoặc mở lại hóa đơn.',
      'post_package_popular': 'Phổ biến nhất',
      'post_package_use_free': 'Dùng gói thường',
      'post_package_choose': 'Chọn gói',
      'post_package_days': '{days} ngày',
      'post_package_free': 'Miễn phí',
      'post_feature_show_normal': 'Hiển thị bình thường',
      'post_feature_highest_priority': 'Ưu tiên cao nhất',
      'post_feature_high_priority': 'Ưu tiên hiển thị cao',
      'post_feature_priority': 'Ưu tiên hiển thị',
      'post_feature_unlimited_images': 'Không giới hạn ảnh',
      'post_feature_max_images': 'Tối đa {max} ảnh',
      'post_feature_badge_gold': 'Badge nổi bật vàng',
      'post_feature_badge_blue': 'Badge VIP xanh',
      'post_feature_banner': 'Xuất hiện trên banner',
      'post_feature_max_videos': '{max} video đăng kèm',
      'post_feature_analytics_detailed': 'Thống kê chi tiết',
      'post_feature_analytics_views': 'Thống kê lượt xem',
      // Messages / Chat
      'chat_title': 'Tin nhắn',
      'chat_search_hint': 'Tìm kiếm cuộc hội thoại...',
      'chat_no_messages': 'Chưa có tin nhắn nào',
      'chat_empty_desc':
          'Bắt đầu cuộc trò chuyện với các chủ trọ để tìm hiểu thêm thông tin.',
      'chat_input_hint': 'Nhập tin nhắn...',
      'chat_send': 'Gửi',
      'chat_reload_tooltip': 'Tải lại',
      'chat_load_error_title': 'Không tải được tin nhắn',
      'chat_empty_title': 'Chưa có cuộc trò chuyện',
      'chat_search_empty_title': 'Không tìm thấy',
      'chat_search_empty_desc':
          'Thử tìm bằng tên người dùng, tin đăng hoặc nội dung khác.',
      'common_retry': 'Thử lại',
      'chat_tab_all': 'Tất cả',
      'chat_tab_unread': 'Chưa đọc',
      'chat_time_just_now': 'Vừa xong',
      'chat_time_minutes_ago': '{minutes} phút trước',
      'chat_time_yesterday': 'Hôm qua',
      'chat_connecting': 'Đang kết nối lại...',
      'chat_listing_unavailable':
          'Tin đăng này không còn khả dụng hoặc đã bị xóa.',
      'chat_error_load_failed': 'Lỗi kết nối máy chủ',
      'chat_active': 'Đang hoạt động',
      'chat_action_call': 'Gọi điện',
      'chat_action_more': 'Tùy chọn khác',
      'chat_no_messages_bubble': 'Chưa có tin nhắn',
      'chat_typing': '{username} đang nhập',
      'chat_listing_closed': 'Tin đăng đã bị đóng. Bạn không thể gửi tin nhắn.',
      'chat_send_error': 'Không thể gửi tin nhắn: {error}',
      'chat_send_retry_failed': 'Thử lại thất bại: {error}',
      'chat_media_send_error': 'Lỗi gửi phương tiện: {error}',
      'chat_attachment_title': 'Gửi phương tiện đính kèm',
      'chat_attachment_image': 'Hình ảnh',
      'chat_attachment_camera': 'Máy ảnh',
      'chat_attachment_document': 'Tài liệu',
      'chat_call_title': 'Gọi cho chủ nhà?',
      'chat_call_desc':
          'Bạn có muốn thực hiện cuộc gọi trực tiếp đến {username} không?',
      'common_cancel': 'Hủy',
      'chat_call_now': 'Gọi ngay',
      'chat_call_starting': 'Đang khởi tạo cuộc gọi thoại...',
      'chat_option_save_listing': 'Lưu tin đăng này',
      'chat_option_saved_success': 'Đã lưu tin đăng vào danh sách yêu thích!',
      'chat_option_block': 'Chặn người dùng này',
      'chat_option_report': 'Báo cáo người dùng',
      'chat_redirecting_listing': 'Đang chuyển hướng tới chi tiết tin đăng...',
      'chat_view_room': 'Xem phòng',
      'chat_month_suffix': 'Tr/tháng',
      'chat_listing_placeholder': 'Tin đăng phòng trọ',
      'chat_online': 'Hoạt động',
      'chat_offline': 'Ngoại tuyến',
      // Onboarding / Preference
      'pref_title': 'Nhu cầu tìm trọ của bạn',
      'pref_subtitle':
          'Chọn vài thông tin cơ bản để Swings House gợi ý phòng phù hợp hơn.',
      'pref_room_type': 'Bạn muốn tìm loại trọ nào?',
      'pref_max_budget': 'Ngân sách tối đa',
      'pref_max_budget_limit': 'triệu/tháng',
      'pref_max_budget_unlimited': 'Từ 15 triệu/tháng trở xuống',
      'pref_preferred_areas': 'Khu vực ưu tiên',
      'pref_amenities': 'Tiện nghi bạn cần',
      'pref_btn_skip': 'Bỏ qua',
      'pref_btn_suggest': 'Xem gợi ý phù hợp',
      'pref_btn_save': 'Lưu thay đổi',
      'pref_update_success': 'Đã cập nhật nhu cầu tìm phòng thành công!',
      // My listings
      'mylistings_title': 'Tin đăng của tôi',
      'mylistings_empty': 'Bạn chưa đăng tin nào',
      'mylistings_empty_desc':
          'Đăng tin phòng trọ của bạn để tiếp cận hàng ngàn người tìm kiếm.',
      'mylistings_tab_active': 'Đang hiển thị',
      'mylistings_tab_pending': 'Chờ duyệt',
      'mylistings_tab_rejected': 'Bị từ chối',
      'mylistings_views': 'lượt xem',
      'mylistings_contacts': 'liên hệ',
      'mylistings_edit': 'Sửa tin',
      'mylistings_delete': 'Xóa',
      'mylistings_confirm_delete': 'Xóa tin đăng này?',
      'mylistings_not_found':
          'Không tìm thấy tin đăng thuộc tài khoản của bạn.',
      'mylistings_status_active': 'Đang hiển thị',
      'mylistings_status_hidden': 'Đang tạm ẩn',
      'mylistings_status_expired': 'Hết hạn',
      'mylistings_status_processing': 'Đang xử lý',
      'mylistings_hide_success':
          'Đã tạm ẩn tin đăng (đánh dấu đã thuê) thành công.',
      'mylistings_show_success': 'Đã hiển thị lại tin đăng thành công.',
      'mylistings_views_label': 'Lượt xem',
      'mylistings_saved_label': 'Lưu',
      'mylistings_reviews_label': 'Đánh giá',
      'mylistings_analytics_title': 'Thống kê tin đăng',
      'mylistings_analytics': 'Thống kê',
      'mylistings_no_analytics': 'Không có thống kê',
      'mylistings_hide_listing': 'Ẩn tin',
      'mylistings_show_listing': 'Hiện lại tin',
      'mylistings_hide_confirm_title': 'Ẩn tin đăng?',
      'mylistings_hide_confirm_desc':
          'Tin sẽ không còn xuất hiện với người đang tìm phòng cho đến khi bạn hiển thị lại.',
      'mylistings_show_confirm_title': 'Hiện lại tin đăng?',
      'mylistings_show_confirm_desc':
          'Tin sẽ xuất hiện trở lại để người tìm phòng có thể xem và liên hệ.',
      'mylistings_normal_package': 'Gói thường',
      'mylistings_saved_count': 'Lượt lưu',
      'mylistings_rating_score': 'Điểm đánh giá',
      'mylistings_reviews_count': 'Số đánh giá',
      'mylistings_engagement': 'Tương tác',
      'mylistings_save_rate': 'Tỷ lệ lưu tin',
      'mylistings_review_rate': 'Tỷ lệ đánh giá',
      'mylistings_total_engagement': 'Tổng tương tác',
      'mylistings_listing_quality': 'Chất lượng tin',
      'mylistings_photo_completeness': 'Độ đầy đủ ảnh',
      'mylistings_contact_info': 'Thông tin liên hệ',
      'mylistings_map_location': 'Vị trí bản đồ',
      'mylistings_available': 'Đã có',
      'mylistings_missing': 'Thiếu',
      'mylistings_locked_title': 'Tin này chưa có thống kê chi tiết',
      'mylistings_locked_buy_vip':
          'Hãy mua gói VIP có thống kê để xem thêm chỉ số.',
      'mylistings_locked_package': 'Gói {package} chưa bật quyền thống kê.',
      'mylistings_empty_posted_desc': 'Các tin đã đăng sẽ xuất hiện tại đây.',
      'favorites_default_title': 'Tin đăng chưa có tiêu đề',
      'favorites_default_type': 'Phòng trọ',
      // My reviews
      'myreviews_remove_title': 'Xóa đánh giá này?',
      'myreviews_remove_desc':
          'Đánh giá này sẽ bị gỡ vĩnh viễn khỏi phòng trọ. Bạn có chắc chắn muốn thực hiện hành động này?',
      'myreviews_remove_success': 'Đã gỡ bài đánh giá thành công!',
      'myreviews_remove_action': 'Gỡ đánh giá',
      'myreviews_landlord_reply': 'Chủ nhà phản hồi',
      'myreviews_empty_title': 'Không có đánh giá',
      'myreviews_empty_desc':
          'Bạn chưa gửi bất kỳ lượt đánh giá chất lượng phòng trọ nào.',
      'myreviews_explore': 'Khám phá phòng trọ ngay',
      'price_million_per_month': '{price} triệu/tháng',
      'price_vnd_per_month': '{price}đ/tháng',
      // About
      'about_features_title': 'Tính năng chính',
      'about_feature_search_title': 'Tìm phòng nhanh',
      'about_feature_search_desc':
          'Lọc phòng theo khu vực, mức giá, diện tích và tiện ích.',
      'about_feature_favorite_title': 'Lưu phòng yêu thích',
      'about_feature_favorite_desc':
          'Giữ lại các phòng phù hợp để xem lại khi cần so sánh.',
      'about_feature_verified_title': 'Thông tin minh bạch',
      'about_feature_verified_desc':
          'Hỗ trợ trạng thái xác thực, đánh giá và thông tin liên hệ.',
      'about_tech_title': 'Công nghệ sử dụng',
      'about_tech_flutter_desc': 'Xây dựng giao diện ứng dụng di động.',
      'about_tech_firebase_desc':
          'Xác thực tài khoản và lưu thông tin người dùng cơ bản.',
      'about_tech_sql_desc':
          'Lưu dữ liệu chính như phòng trọ, người dùng và giao dịch.',
      'about_tech_cloudinary_desc': 'Quản lý ảnh phòng trọ và ảnh đại diện.',
      'about_project_title': 'Thông tin dự án',
      'about_app_name': 'Tên ứng dụng',
      'about_version': 'Phiên bản',
      'about_purpose': 'Mục đích',
      'about_purpose_value': 'Hỗ trợ tìm kiếm và đăng tin phòng trọ',
      'about_support_contact': 'Liên hệ hỗ trợ',
      'about_subtitle': 'Ứng dụng tìm kiếm phòng trọ',
      'about_intro':
          'SWING HOUSE giúp người thuê tìm phòng phù hợp nhanh hơn, đồng thời hỗ trợ chủ trọ quản lý tin đăng, hình ảnh và trạng thái phòng một cách rõ ràng.',
      'about_email_subject': 'Hỗ trợ ứng dụng SWING HOUSE',
      'about_email_open_failed':
          'Chưa mở được ứng dụng email trên thiết bị này',
      // Invoices / Payments
      'invoice_title': 'Hóa đơn & Thanh toán',
      'invoice_empty': 'Chưa có hóa đơn nào',
      'invoice_detail_title': 'Chi tiết hóa đơn',
      'invoice_status_cancelled': 'Đã hủy',
      'invoice_method': 'Phương thức',
      'invoice_amount': 'Số tiền',
      'invoice_date': 'Ngày tạo',
      'invoice_due': 'Hạn thanh toán',
      'invoice_vip_title': 'Mua gói tin VIP',
      'invoice_vip_select': 'Chọn gói tin',
      // Support & About
      'support_title': 'Trung tâm hỗ trợ',
      'about_title': 'Về ứng dụng',
    },
    'en': {
      'settings_title': 'System Settings',
      'nav_home': 'Home',
      'nav_favorites': 'Favorites',
      'nav_post': 'Post',
      'nav_chat': 'Messages',
      'nav_profile': 'Profile',
      'leave_draft_title': 'Discard draft?',
      'leave_draft_desc':
          'You are editing a listing draft. If you leave this page, unsaved information will be lost.',
      'stay': 'Stay',
      'leave_page': 'Leave',
      'notifications_off_title': 'Notifications are off',
      'notifications_off_desc':
          'Turn notifications back on in System Settings to see new updates.',
      'profile_account': 'ACCOUNT',
      'profile_activity': 'ACTIVITY',
      'profile_support': 'SUPPORT',
      'profile_personal_info': 'Personal information',
      'profile_change_password': 'Change password',
      'profile_verify_account': 'Account verification',
      'profile_preferences': 'Room preferences',
      'profile_saved_rooms': 'Saved rooms',
      'profile_my_reviews': 'My reviews',
      'profile_search_history': 'Search history',
      'profile_my_listings': 'My listings',
      'profile_invoices': 'Invoices & Payments',
      'profile_support_center': 'Support center',
      'profile_report_issue': 'Report an issue',
      'profile_rate_app': 'Rate app',
      'profile_about_app': 'About app',
      'profile_logout': 'Log out',
      'profile_login_now': 'Log in now',
      'profile_register_now': 'Create new account',
      'profile_not_logged_title': 'You are not logged in',
      'profile_not_logged_desc':
          'Log in to manage your account, save favorite rooms, and track listings.',
      'profile_favorites_count': 'Favorites',
      'profile_joined_date': 'Joined',
      'profile_reviews_count': 'Reviews',
      'profile_landlord': 'Landlord',
      'profile_tenant': 'Tenant',
      'profile_verified': 'Verified',
      'profile_unverified': 'Unverified',
      'profile_logout_title': 'Log out?',
      'profile_logout_desc':
          'Are you sure you want to log out of this account?',
      'profile_edit_info': 'Edit information',
      'profile_full_name': 'Full name',
      'profile_phone': 'Phone number',
      'profile_save_changes': 'Save changes',
      'profile_name_required': 'Full name cannot be empty',
      'profile_update_success': 'Information updated successfully',
      'profile_app_rating_thanks': 'Thank you for rating the app.',
      'profile_feedback': 'Feedback',
      'profile_send_rating': 'Submit rating',
      'profile_update_rating': 'Update rating',
      'profile_rating_hint':
          'What do you like, or what should the app improve?',
      'favorites_title': 'Saved rooms',
      'favorites_removed': 'Removed this room from saved list',
      'favorites_search_hint': 'Search saved rooms...',
      'favorites_sort_newest': 'Newest saved',
      'favorites_sort_price_asc': 'Price low to high',
      'favorites_sort_price_desc': 'Price high to low',
      'favorites_sort_area': 'Area',
      'favorites_retry': 'Retry',
      'favorites_empty_title': 'No saved rooms yet',
      'favorites_empty_desc':
          'Save rooms you like so you can quickly review them here.',
      'favorites_find_now': 'Find rooms now',
      'favorites_no_result': 'No results',
      'favorites_try_other': 'Try another keyword',
      'favorites_sort_by': 'Sort by',
      'favorites_new_badge': 'NEW',
      'favorites_saved_time': 'Saved',
      'favorites_verified': 'Verified',
      'favorites_contact': 'Contact',
      'favorites_undo': 'Undo',
      'favorites_month_suffix': '/month',
      'favorites_load_error': 'Failed to load favorites list',
      'favorites_retry_desc': 'Please try again.',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'days_ago': '{days} days ago',
      'password_current': 'Current password',
      'password_current_hint': 'Enter current password',
      'password_new': 'New password',
      'password_new_hint': 'Enter new password',
      'password_confirm': 'Confirm new password',
      'password_confirm_hint': 'Re-enter new password',
      'password_update': 'Update password',
      'password_success': 'Password changed successfully!',
      'password_weak_warning':
          'The new password does not meet security requirements!',
      'password_strength': 'Password strength: ',
      'password_strong': 'Strong',
      'password_medium': 'Medium',
      'password_weak': 'Weak',
      'password_empty_strength': 'Not entered',
      'password_min_length': 'At least 8 characters',
      'password_has_number': 'Contains at least 1 number (0-9)',
      'password_has_capital': 'Contains at least 1 uppercase letter (A-Z)',
      'password_current_required': 'Please enter your current password',
      'password_new_required': 'Please enter a new password',
      'password_same_old':
          'New password cannot be the same as the old password',
      'password_confirm_required': 'Please confirm the new password',
      'password_confirm_mismatch': 'Confirmation password does not match',
      'verify_gateways_title': 'Secure Link Portals',
      'verify_email': 'Email Verification',
      'verify_email_unlinked': 'Email not linked',
      'verify_email_verified': 'Verified',
      'verify_email_verify_now': 'Verify Now',
      'verify_phone': 'Phone Number',
      'verify_phone_unverified': 'Phone number not verified',
      'verify_phone_verified': 'Verified',
      'verify_phone_verify_now': 'Verify Now',
      'verify_google': 'Google Account',
      'verify_google_desc': 'Link Google account for quick login',
      'verify_facebook': 'Facebook Account',
      'verify_facebook_desc': 'Link Facebook account for security',
      'verify_action_link': 'Link',
      'verify_action_unlink': 'Unlink',
      'verify_trust_title': 'Account Trust Level',
      'verify_trust_level_label': 'Level: {level}',
      'verify_trust_level_absolute': 'Absolute',
      'verify_trust_level_high': 'Very High',
      'verify_trust_level_medium': 'Medium',
      'verify_trust_level_low': 'Low',
      'verify_trust_success_desc':
          'Excellent! Your account has reached absolute trust level and activated the Verified Badge.',
      'verify_trust_warning_desc':
          'Please verify your phone number and link social accounts to reach 100% trust level!',
      'verify_security_commitment':
          'Swings House guarantees 100% security for your linked account data. This linking is only used to increase the credibility of the information displayed on your room listing.',
      'verify_confirm_unlink_google_title': 'Unlink Google Account',
      'verify_confirm_unlink_google_desc':
          'Are you sure you want to unlink this Google account?',
      'verify_confirm_unlink_facebook_title': 'Unlink Facebook Account',
      'verify_confirm_unlink_facebook_desc':
          'Are you sure you want to unlink this Facebook account?',
      'verify_success_google_link': 'Linked Google account successfully!',
      'verify_success_facebook_link': 'Linked Facebook account successfully!',
      'verify_success_phone_verify': 'Verified phone number successfully!',
      'verify_email_sent_mock':
          'Verification request sent! Simulated Email verification successfully.',
      'verify_dialog_cancel': 'Cancel',
      'verify_otp_title': 'Enter OTP Verification Code',
      'verify_otp_sent_to': 'OTP code has been sent to {phone}',
      'verify_otp_instruction':
          'Swings House will send a 6-digit OTP code to this phone number.',
      'verify_phone_input_hint': 'Enter your phone number',
      'verify_otp_get_code': 'Get OTP Code',
      'verify_otp_resend_countdown': 'Resend code in {seconds}s',
      'verify_otp_not_received': 'Didn\'t receive code? ',
      'verify_otp_resend_now': 'Resend now',
      'verify_otp_confirm': 'Confirm',
      'verify_otp_invalid_phone': 'Please enter a valid phone number!',
      'verify_otp_invalid_otp': 'Please enter all 6 OTP digits!',
      'verify_email_input_hint': 'Enter your email address',
      'verify_otp_sent_to_email': 'OTP code has been sent to email {email}',
      'verify_otp_instruction_email':
          'Swings House will send a 6-digit OTP code to this email.',
      'verify_otp_invalid_email': 'Please enter a valid email address!',
      'verify_success_email_verify': 'Verified email address successfully!',
      'search_history_empty_title': 'No search history',
      'search_history_empty_desc':
          'You have not searched for any rooms recently.',
      'search_history_suggestions': 'Popular suggestions',
      'report_type_account': 'Account',
      'report_type_listing': 'Listing/room',
      'report_type_payment': 'Payment',
      'report_type_chat': 'Messages/contact',
      'report_type_app': 'App error',
      'report_type_other': 'Other',
      'report_intro':
          'Please describe the issue clearly. SWING HOUSE will use this information to investigate and support you faster.',
      'report_issue_type': 'Issue type',
      'report_content': 'Report content',
      'report_title_label': 'Title',
      'report_title_hint': 'Example: Cannot log in',
      'report_title_required': 'Please enter an issue title',
      'report_desc_label': 'Detailed description',
      'report_desc_hint':
          'Where were you using the app, and what error appeared?',
      'report_desc_required': 'Please describe at least 10 characters',
      'report_contact_label': 'Email or phone number',
      'report_contact_hint': 'So support can contact you if needed',
      'report_device_title': 'Include device information',
      'report_device_desc': 'Helps identify issues by app version and device.',
      'report_submit': 'Submit report',
      'report_success': 'Your issue report has been recorded',
      'yes': 'Yes',
      'no': 'No',
      'support_search_hint': 'Search frequently asked questions...',
      'support_need_help': 'Still need help?',
      'support_contact_desc': 'Contact us directly through the channels below',
      'support_report_bug': 'Report bug',
      'support_no_result': 'No results found',
      'interface_section': 'INTERFACE & CONFIGURATION',
      'app_theme': 'App Theme',
      'theme_mode_active': 'Applying: ',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System',
      'push_notifications': 'Push Notifications',
      'notifications_desc': 'Enable messages & payment invoices',
      'language': 'Language',
      'lang_active': 'Selected: ',
      'lang_vi': 'Tiếng Việt',
      'lang_en': 'English',
      'data_section': 'DATA CLEANING',
      'clear_search': 'Clear Search History',
      'clear_search_desc': 'Clear recent search keywords',
      'clear_cache': 'Clear App Cache',
      'clear_cache_desc': 'Free up cache data',
      'account_section': 'ACCOUNT',
      'change_password': 'Change Password',
      'change_password_desc': 'Update your login password',
      'deactivate_account': 'Deactivate Account',
      'deactivate_account_desc': 'Request to temporarily lock account',
      'cancel': 'Cancel',
      'clear': 'Clear',
      'confirm': 'Agree',
      'clear_search_confirm_title': 'Clear search history?',
      'clear_search_confirm_desc':
          'Are you sure you want to clear all recent search history? This action cannot be undone.',
      'clear_search_success': 'Search history cleared successfully',
      'clear_cache_confirm_title': 'Clear app cache?',
      'clear_cache_confirm_desc':
          'This action will clear cached images and temporary files to free up storage space. Original files are not affected.',
      'clear_cache_success': 'App cache cleared successfully',
      'deactivate_confirm_title': 'WARNING: Deactivate Account?',
      'deactivate_confirm_desc':
          'Your account will be temporarily locked. You will not be able to search, contact, or post room listings. To reactivate or permanently delete data, please contact Swings House support.',
      'deactivate_confirm_btn': 'Agree to Deactivate',
      'deactivate_success': 'Your account has been temporarily deactivated.',
      'dialog_clean': 'Clean',
      // Home & Filter
      'home_hello': 'Hello 👋',
      'home_welcome_question': 'Which room do you want to find?',
      'home_search_hint': 'Search rooms, area...',
      'home_category_all': 'All',
      'home_filter_title': 'Search Filter',
      'home_filter_reset': 'Reset',
      'home_filter_apply': 'Apply',
      'home_filter_type': 'Room Type',
      'home_filter_price': 'Price Range (M/month)',
      'home_filter_price_unlimited': 'Unlimited',
      'home_filter_area': 'Area (sqm)',
      'home_filter_amenity': 'Amenities',
      'home_filter_gender': 'Gender Limit',
      'home_filter_gender_all': 'All genders',
      'home_filter_gender_male': 'Male only',
      'home_filter_gender_female': 'Female only',
      'home_filter_gender_none': 'No limit',
      'home_no_listings': 'No matching listings found',
      'home_load_more': 'Load more',
      'home_location_picker': 'Select location',
      'home_type_phong_tro': 'Student Room',
      'home_type_can_ho': 'Service Apt',
      'home_type_o_ghep': 'Shared Room',
      'home_type_nha_can': 'Whole House',
      'home_categories_title': 'Categories',
      'home_type_phong_tro_short': 'Student\nRoom',
      'home_type_can_ho_short': 'Service\nApt',
      'home_type_o_ghep_short': 'Shared\nRoom',
      'home_type_nha_can_short': 'Whole\nHouse',
      'home_price_unit_short': '/mo',
      'home_price_unit_long': '/month',
      'home_filter_nearby': 'Nearby',
      'home_filter_by_budget': 'By budget',
      'home_filter_new': 'New',
      'home_filter_allow_pet': 'Pets allowed',
      'home_filter_vip': 'VIP',
      'home_location_all': 'All regions',
      'home_location_select_title': 'Select region',
      'home_filter_active_banner': 'Filters applied',
      'home_filter_clear': 'Clear',
      'home_pref_banner_prefix': 'Preferred: {preferences}',
      'home_pref_banner_empty':
          'Suggestions personalized based on your preferences',
      'home_pref_banner_edit': 'Edit',
      'home_pref_budget_under': 'Under {budget}M',
      'home_sql_fallback':
          'Cannot connect to SQL database, displaying mock data.',
      'home_featured_empty': 'No matching featured listings',
      'home_featured_title': '⭐  Featured',
      'home_suggested_title': '🎯  Suggested for you',
      'home_view_more': 'See more',
      'home_view_all': 'See all',
      'home_search_results_count': '{count} results for "{query}"',
      'home_search_empty_title': 'No results found',
      'home_search_empty_desc':
          'Try searching with another keyword\nor adjusting the filters',
      'home_status_rented': 'Rented',
      'home_status_hot': '🔥 Hot',
      'home_status_available': 'Available',
      'home_badge_featured': 'FEATURED',
      'home_badge_new': 'NEW',
      'home_banner_fallback_title': 'Premium Rooms',
      'home_banner_fallback_subtitle': 'Verified · Real Photos · Secure',
      // Amenities
      'Wifi': 'Wi-Fi',
      'Điều hòa': 'Air Conditioner',
      'Thang máy': 'Elevator',
      'Máy giặt': 'Washing Machine',
      'Ban công': 'Balcony',
      'Bảo vệ': 'Security',
      'Sân vườn': 'Garden',
      'Nuôi thú': 'Pet Friendly',
      // Notifications
      'notif_title': 'Notifications',
      'notif_unread_suffix': 'unread',
      'notif_empty': 'No notifications yet',
      'notif_empty_desc':
          'Updates on listings, messages, and payments will appear here.',
      'notif_load_failed': 'Failed to load notifications',
      'notif_retry': 'Retry',
      'notif_just_now': 'Just now',
      'notif_mins_ago': 'minutes ago',
      'notif_hours_ago': 'hours ago',
      'notif_days_ago': 'days ago',
      // Listing Create
      'post_step_title_1': 'Type & Title',
      'post_step_title_2': 'Room Photos (6 max)',
      'post_step_title_3': 'Address',
      'post_step_title_4': 'Room Details',
      'post_step_title_5': 'Price & Amenities',
      'post_success': 'Listing submitted successfully! Awaiting approval.',
      'post_failed': 'Failed to submit listing',
      'post_header_title': 'Post listing',
      'post_header_edit_title': 'Edit listing',
      'post_header_step': 'Step {step}/{total} · {title}',
      'post_img_cover': 'Cover photo',
      'post_img_extra': 'Extra photo',
      'post_img_add': 'Add photo',
      'post_video_add': 'Add video',
      'post_video_limit': 'Max',
      'post_validation_type': 'Please select a room type.',
      'post_validation_title': 'Please enter a listing title.',
      'post_validation_cover': 'Please add a cover photo for approval.',
      'post_validation_province': 'Please select a province.',
      'post_validation_district': 'Please select a district.',
      'post_validation_ward': 'Please select a ward.',
      'post_validation_street': 'Please enter the detailed address.',
      'post_validation_area': 'Please enter a valid area.',
      'post_validation_occupants':
          'Please enter a valid maximum occupants count.',
      'post_validation_price': 'Please enter a valid rental price.',
      'post_validation_image_limit':
          'Selected package only allows up to {max} photos.',
      'post_validation_video_limit':
          'Selected package only allows up to {max} videos.',
      'post_discard_draft_title': 'Discard draft?',
      'post_discard_draft_desc':
          'You are editing a listing draft. If you leave this page, unsaved information will be lost.',
      'post_draft_stay': 'Stay',
      'post_draft_leave': 'Leave',
      'post_btn_prev': 'Back',
      'post_btn_next': 'Next',
      'post_btn_submit': 'Post now',
      'post_title': 'Post a Listing',
      'post_step_prefix': 'Step',
      'post_help': 'Help',
      'post_help_sheet_title': 'Posting help',
      'post_help_sheet_subtitle': 'Tips for: {title}',
      'post_help_open_support': 'Support center',
      'post_help_report_issue': 'Report issue',
      'post_help_step1_tip1':
          'Choose the correct room type so renters can filter and find the listing faster.',
      'post_help_step1_tip2':
          'The title should mention the area, main advantage, and standout price.',
      'post_help_step1_tip3':
          'A specific description about furniture, hours, and fees reduces repeated questions.',
      'post_help_step2_tip1':
          'The cover photo should be bright, clear, wide, and show the main space.',
      'post_help_step2_tip2':
          'Add photos of the bathroom, kitchen, parking area, and entrance to increase trust.',
      'post_help_step2_tip3':
          'Video is only available for packages that support video; check the selected package if video slots are hidden.',
      'post_help_step3_tip1':
          'A complete address makes the map and area search more accurate.',
      'post_help_step3_tip2':
          'If the map cannot resolve the address, you can still pick the location manually.',
      'post_help_step3_tip3':
          'Avoid publishing private room numbers in the public description unless necessary.',
      'post_help_step4_tip1':
          'Area, max occupants, and floor should match reality to avoid complaints.',
      'post_help_step4_tip2':
          'Available date helps renters know whether the listing fits their timeline.',
      'post_help_step4_tip3':
          'Pet policy should be clear from the start if there are landlord limits.',
      'post_help_step5_tip1':
          'Enter rent in VND per month, without dots or text in the price field.',
      'post_help_step5_tip2':
          'Fill electricity, water, internet, and parking so renters can estimate total cost.',
      'post_help_step5_tip3':
          'Select the right amenities so the listing appears in relevant search filters.',
      'post_label_type': 'Type',
      'post_label_photos': 'Photos',
      'post_label_address': 'Address',
      'post_label_details': 'Details',
      'post_label_pricing': 'Pricing',
      'post_room_type_section': 'Room Type',
      'post_basic_info_section': 'Basic Info',
      'post_title_label': 'Listing Title',
      'post_title_hint': 'e.g., Cheap room with full furniture in Binh Thanh',
      'post_desc_label': 'Detailed Description',
      'post_desc_hint': 'Describe highlights, nearby amenities...',
      'post_package_section': 'Post Package',
      'post_package_loading': 'Loading packages...',
      'post_package_error': 'Failed to load packages',
      'post_package_reload': 'Reload Packages',
      'post_img_banner_title': 'Room Photos - Max {max} photos',
      'post_img_banner_desc':
          '- Gói {package} permits {max} photos in current tier\n- First photo is the cover photo on list view\n- JPG/PNG formats, max 5 MB per image',
      'post_img_list_title': 'Photo List',
      'post_img_count': '{current} / {max} photos',
      'post_img_add_cover': 'Add cover photo',
      'post_img_add_extra': 'Photo {index}',
      'post_img_click_gallery': 'Tap to pick from gallery',
      'post_img_tip':
          'Tip: Bright, clear photos from various angles boost contacts by 3x!',
      'post_video_not_supported': 'Current package does not support video.',
      'post_video_section': 'Room Video',
      'post_video_list': 'Video List',
      'post_video_count': '{current} / {max} videos',
      'post_video_hint': 'Choose video {index}',
      'post_video_specs': 'MP4/MOV/WebM supported, max 100 MB per video.',
      'post_address_section': 'Room Address',
      'post_select_field': 'Select {field}',
      'post_province_label': 'Province / City',
      'post_district_label': 'District / County',
      'post_ward_label': 'Ward / Commune',
      'post_street_label': 'Detailed Address',
      'post_street_hint': 'House number, street name...',
      'post_map_resolving': 'Resolving address...',
      'post_map_select_hint': 'Tap to select location on map',
      'post_map_tap_instruction': 'Tap on the map to set location',
      'post_map_selected_pos': 'Selected Position',
      'post_map_use_pos': 'Use This Position',
      'post_map_no_service': 'Please enable location services on your device.',
      'post_map_no_permission': 'Location permission has not been granted.',
      'post_map_err_get_pos': 'Failed to retrieve current location.',
      'post_map_search_hint': 'Search address on OpenStreetMap',
      'post_map_search_empty': 'No matching address found.',
      'post_map_search_error': 'Could not search address. Please try again.',
      'post_details_area_section': 'Area & Floor',
      'post_details_area_label': 'Area (m2)',
      'post_details_occupants_label': 'Max Occupants',
      'post_details_occupants_unit': 'people',
      'post_details_floor_label': 'Floor',
      'post_details_floor_unit': 'floor',
      'post_details_total_floors_label': 'Total Floors',
      'post_details_available_section': 'Available From',
      'post_details_available_hint': 'Select availability date',
      'post_details_date_format': 'Date {day}/{month}/{year}',
      'post_policy_section': 'Policy',
      'post_policy_pet_title': 'Pets Allowed',
      'post_policy_pet_desc': 'Dogs, cats, small pets...',
      'post_price_section': 'Rental Price',
      'post_price_label': 'Rental price per month (VND)',
      'post_price_unit': '/month',
      'post_services_section': 'Service Fees',
      'post_service_electric': 'Electricity (đ/kWh)',
      'post_service_water': 'Water (đ/m3)',
      'post_service_internet': 'Internet (đ/month)',
      'post_service_parking': 'Parking (đ/month)',
      'post_amenities_section': 'Amenities Included',
      'post_amenities_empty': 'No amenities available.',
      'post_preview_title': 'Listing Preview',
      'post_preview_no_title': 'No title entered',
      'post_preview_no_type': 'No type selected',
      'post_preview_no_price': '---',
      'post_preview_no_address': 'No address entered',
      'post_preview_images': '{count} photos',
      'post_preview_videos': '{count} videos',
      'post_submitting': 'Posting listing...',
      'post_img_slot_cover': 'Slot 1 (Cover)',
      'post_img_slot_index': 'Slot {index}',
      'post_tooltip_make_cover': 'Set as cover',
      'post_tooltip_change_img': 'Change image',
      'post_tooltip_delete': 'Delete',
      'post_video_none': 'No video',
      'post_package_desc': '{photos} photos • {videos} • {days} days',
      'post_img_limit_reached':
          'Package {package} only allows a maximum of {max} images.',
      'post_package_current': 'current package',
      'post_address_resolve_error':
          'Location selected, but address could not be auto-resolved.',
      'post_img_upload_timeout':
          'Listing created, but image upload timed out. You can still purchase the VIP package.',
      'post_img_upload_failed':
          'Listing created, but image upload failed. You can still purchase the VIP package.',
      'post_video_upload_timeout':
          'Listing created, but video upload timed out. You can add videos later.',
      'post_video_upload_failed': 'Listing created, but video upload failed.',
      'post_area_unit': 'sqm',
      'invoice_load_failed': 'Failed to load invoices',
      'invoice_retry': 'Retry',
      'invoice_empty_title': 'No invoices yet',
      'invoice_empty_desc':
          'Invoices for your posting packages will appear here.',
      'invoice_view_packages': 'View packages',
      'invoice_summary_total': 'Total',
      'invoice_summary_paid': 'Paid',
      'invoice_summary_pending': 'Pending',
      'invoice_card_code': 'Invoice Code',
      'invoice_card_type': 'Invoice Type',
      'invoice_card_amount': 'Amount',
      'invoice_card_created': 'Date created',
      'invoice_card_note': 'Note',
      'invoice_btn_view_listing': 'View listing',
      'invoice_btn_pay': 'Pay',
      'invoice_btn_processing': 'Processing',
      'invoice_btn_view_bill': 'View bill',
      'invoice_status_paid': 'Paid',
      'invoice_status_pending': 'Pending',
      'invoice_status_failed': 'Failed',
      'invoice_status_refund': 'Refunded',
      'invoice_status_unknown': 'Status #{id}',
      'invoice_type_post_package': 'Posting Package',
      'invoice_pay_success': 'Payment successful. VIP package activated.',
      'invoice_bill_title': 'SWING HOUSE - PAYMENT BILL',
      'invoice_bill_code': 'Invoice Code: {code}',
      'invoice_bill_type': 'Invoice Type: {type}',
      'invoice_bill_status': 'Status: {status}',
      'invoice_bill_amount': 'Amount: {amount}',
      'invoice_bill_created': 'Date created: {date}',
      'invoice_bill_due': 'Due date: {date}',
      'invoice_bill_listing': 'Listing ID: #{id}',
      'invoice_bill_note': 'Note: {note}',
      'invoice_bill_thank_you': 'Thank you for using SWING HOUSE.',
      'invoice_bill_total_payment': 'Total Payment',
      'invoice_btn_copy': 'Copy',
      'invoice_btn_export': 'Export file',
      'invoice_btn_view_related_listing': 'View related listing',
      'invoice_export_success': 'Bill exported and copied. File: {path}',
      'invoice_export_failed': 'Could not export bill: {error}',
      'invoice_copy_success': 'Bill copied.',
      'invoice_bill_due_label': 'Due Date',
      'invoice_bill_listing_label': 'Listing ID',
      'post_package_must_post_first':
          'Please post a listing before buying a VIP package.',
      'invoice_dialog_created_title': 'Invoice Created',
      'invoice_dialog_code': 'Invoice Code: {code}',
      'invoice_dialog_amount': 'Amount: {amount}',
      'invoice_dialog_success_desc':
          'Upon successful payment, package {package} will be activated for the listing.',
      'invoice_dialog_btn_later': 'Pay later',
      'invoice_dialog_btn_simulate': 'Simulate payment',
      'invoice_pay_now': 'Pay with PayOS',
      'invoice_qr_title': 'Scan PayOS QR',
      'invoice_qr_desc':
          'Use your banking app to scan this QR code and complete payment.',
      'invoice_qr_unavailable':
          'This invoice does not have a QR code yet. Open PayOS checkout to pay.',
      'invoice_open_checkout': 'Open PayOS checkout',
      'invoice_open_checkout_failed': 'Could not open PayOS checkout.',
      'invoice_payment_link_missing':
          'This invoice does not have a PayOS payment link.',
      'invoice_checking_payment': 'Checking payment...',
      'invoice_waiting_payment':
          'After payment, this screen will update automatically.',
      'invoice_sync_payment_failed':
          'Could not check payment status yet. Please wait or reopen the invoice.',
      'post_package_popular': 'Most popular',
      'post_package_use_free': 'Use free package',
      'post_package_choose': 'Select package',
      'post_package_days': '{days} days',
      'post_package_free': 'Free',
      'post_feature_show_normal': 'Normal visibility',
      'post_feature_highest_priority': 'Highest priority',
      'post_feature_high_priority': 'High visibility',
      'post_feature_priority': 'Priority visibility',
      'post_feature_unlimited_images': 'Unlimited photos',
      'post_feature_max_images': 'Max {max} photos',
      'post_feature_badge_gold': 'Gold featured badge',
      'post_feature_badge_blue': 'Blue VIP badge',
      'post_feature_banner': 'Appear on banner',
      'post_feature_max_videos': '{max} videos included',
      'post_feature_analytics_detailed': 'Detailed analytics',
      'post_feature_analytics_views': 'View analytics',
      // Messages / Chat
      'chat_title': 'Messages',
      'chat_search_hint': 'Search conversations...',
      'chat_no_messages': 'No messages yet',
      'chat_empty_desc':
          'Start a chat with landlords to find out more details.',
      'chat_input_hint': 'Type a message...',
      'chat_send': 'Send',
      'chat_reload_tooltip': 'Reload',
      'chat_load_error_title': 'Failed to load messages',
      'chat_empty_title': 'No conversations yet',
      'chat_search_empty_title': 'No results found',
      'chat_search_empty_desc':
          'Try searching by username, listing title, or other content.',
      'common_retry': 'Retry',
      'chat_tab_all': 'All',
      'chat_tab_unread': 'Unread',
      'chat_time_just_now': 'Just now',
      'chat_time_minutes_ago': '{minutes} minutes ago',
      'chat_time_yesterday': 'Yesterday',
      'chat_connecting': 'Reconnecting...',
      'chat_listing_unavailable':
          'This listing is no longer available or has been deleted.',
      'chat_error_load_failed': 'Server connection error',
      'chat_active': 'Active',
      'chat_action_call': 'Call',
      'chat_action_more': 'More options',
      'chat_no_messages_bubble': 'No messages',
      'chat_typing': '{username} is typing',
      'chat_listing_closed': 'Listing closed. You cannot send messages.',
      'chat_send_error': 'Could not send message: {error}',
      'chat_send_retry_failed': 'Retry failed: {error}',
      'chat_media_send_error': 'Failed to send media: {error}',
      'chat_attachment_title': 'Send media attachment',
      'chat_attachment_image': 'Image',
      'chat_attachment_camera': 'Camera',
      'chat_attachment_document': 'Document',
      'chat_call_title': 'Call landlord?',
      'chat_call_desc': 'Do you want to place a direct call to {username}?',
      'common_cancel': 'Cancel',
      'chat_call_now': 'Call now',
      'chat_call_starting': 'Starting voice call...',
      'chat_option_save_listing': 'Save this listing',
      'chat_option_saved_success': 'Listing saved to favorites!',
      'chat_option_block': 'Block this user',
      'chat_option_report': 'Report user',
      'chat_redirecting_listing': 'Redirecting to listing details...',
      'chat_view_room': 'View Room',
      'chat_month_suffix': 'M/month',
      'chat_listing_placeholder': 'Room Listing',
      'chat_online': 'Active',
      'chat_offline': 'Offline',
      // Onboarding / Preference
      'pref_title': 'Your room preferences',
      'pref_subtitle':
          'Choose some basic info so Swings House can suggest better rooms.',
      'pref_room_type': 'What type of room are you looking for?',
      'pref_max_budget': 'Maximum budget',
      'pref_max_budget_limit': 'M/month',
      'pref_max_budget_unlimited': 'Under 15 M/month',
      'pref_preferred_areas': 'Preferred areas',
      'pref_amenities': 'Amenities you need',
      'pref_btn_skip': 'Skip',
      'pref_btn_suggest': 'See suggestions',
      'pref_btn_save': 'Save changes',
      'pref_update_success': 'Updated room preferences successfully!',
      // My listings
      'mylistings_title': 'My listings',
      'mylistings_empty': 'You have not posted any listings',
      'mylistings_empty_desc':
          'Post your room listing to reach thousands of seekers.',
      'mylistings_tab_active': 'Active',
      'mylistings_tab_pending': 'Pending',
      'mylistings_tab_rejected': 'Rejected',
      'mylistings_views': 'views',
      'mylistings_contacts': 'contacts',
      'mylistings_edit': 'Edit',
      'mylistings_delete': 'Delete',
      'mylistings_confirm_delete': 'Delete this listing?',
      'mylistings_not_found': 'No listing in your account was found.',
      'mylistings_status_active': 'Visible',
      'mylistings_status_hidden': 'Hidden',
      'mylistings_status_expired': 'Expired',
      'mylistings_status_processing': 'Processing',
      'mylistings_hide_success':
          'Listing hidden and marked as rented successfully.',
      'mylistings_show_success': 'Listing is visible again.',
      'mylistings_views_label': 'Views',
      'mylistings_saved_label': 'Saved',
      'mylistings_reviews_label': 'Reviews',
      'mylistings_analytics_title': 'Listing analytics',
      'mylistings_analytics': 'Analytics',
      'mylistings_no_analytics': 'No analytics',
      'mylistings_hide_listing': 'Hide listing',
      'mylistings_show_listing': 'Show listing',
      'mylistings_hide_confirm_title': 'Hide this listing?',
      'mylistings_hide_confirm_desc':
          'People looking for rooms will not see this listing until you show it again.',
      'mylistings_show_confirm_title': 'Show this listing again?',
      'mylistings_show_confirm_desc':
          'The listing will be visible again so people can view and contact you.',
      'mylistings_normal_package': 'Standard package',
      'mylistings_saved_count': 'Saves',
      'mylistings_rating_score': 'Rating score',
      'mylistings_reviews_count': 'Review count',
      'mylistings_engagement': 'Engagement',
      'mylistings_save_rate': 'Save rate',
      'mylistings_review_rate': 'Review rate',
      'mylistings_total_engagement': 'Total engagement',
      'mylistings_listing_quality': 'Listing quality',
      'mylistings_photo_completeness': 'Photo completeness',
      'mylistings_contact_info': 'Contact information',
      'mylistings_map_location': 'Map location',
      'mylistings_available': 'Available',
      'mylistings_missing': 'Missing',
      'mylistings_locked_title': 'This listing has no detailed analytics yet',
      'mylistings_locked_buy_vip':
          'Buy a VIP package with analytics to see more metrics.',
      'mylistings_locked_package':
          'Package {package} has not enabled analytics.',
      'mylistings_empty_posted_desc': 'Your posted listings will appear here.',
      'favorites_default_title': 'Listing has no title',
      'favorites_default_type': 'Room',
      // My reviews
      'myreviews_remove_title': 'Delete this review?',
      'myreviews_remove_desc':
          'This review will be permanently removed from the listing. Are you sure you want to continue?',
      'myreviews_remove_success': 'Review removed successfully!',
      'myreviews_remove_action': 'Remove review',
      'myreviews_landlord_reply': 'Landlord reply',
      'myreviews_empty_title': 'No reviews',
      'myreviews_empty_desc':
          'You have not submitted any room quality reviews yet.',
      'myreviews_explore': 'Explore rooms now',
      'price_million_per_month': '{price}M/month',
      'price_vnd_per_month': '{price} VND/month',
      // About
      'about_features_title': 'Main features',
      'about_feature_search_title': 'Fast room search',
      'about_feature_search_desc':
          'Filter rooms by area, price, size, and amenities.',
      'about_feature_favorite_title': 'Save favorite rooms',
      'about_feature_favorite_desc':
          'Keep suitable rooms so you can compare them later.',
      'about_feature_verified_title': 'Transparent information',
      'about_feature_verified_desc':
          'Support verification status, reviews, and contact information.',
      'about_tech_title': 'Technology stack',
      'about_tech_flutter_desc': 'Build the mobile application interface.',
      'about_tech_firebase_desc':
          'Authenticate accounts and store basic user information.',
      'about_tech_sql_desc':
          'Store core data such as listings, users, and transactions.',
      'about_tech_cloudinary_desc': 'Manage listing photos and profile images.',
      'about_project_title': 'Project information',
      'about_app_name': 'App name',
      'about_version': 'Version',
      'about_purpose': 'Purpose',
      'about_purpose_value': 'Support room search and listing posting',
      'about_support_contact': 'Support contact',
      'about_subtitle': 'Room search application',
      'about_intro':
          'SWING HOUSE helps renters find suitable rooms faster while helping landlords manage listings, images, and room status clearly.',
      'about_email_subject': 'SWING HOUSE app support',
      'about_email_open_failed': 'Could not open an email app on this device',
      // Invoices / Payments
      'invoice_title': 'Invoices & Payments',
      'invoice_empty': 'No invoices yet',
      'invoice_detail_title': 'Invoice Details',
      'invoice_status_cancelled': 'Cancelled',
      'invoice_method': 'Method',
      'invoice_amount': 'Amount',
      'invoice_date': 'Date created',
      'invoice_due': 'Due date',
      'invoice_vip_title': 'Buy VIP package',
      'invoice_vip_select': 'Select package',
      // Support & About
      'support_title': 'Support Center',
      'about_title': 'About App',
    }
  };

  /// Translate a given key to the currently active language.
  static String tr(String key) {
    final lang = languageNotifier.value;
    return _localizedValues[lang]?[key] ?? key;
  }
}

/// Extension on [String] to make translation clean.
extension TranslationExtension on String {
  String get tr => AppLocalizations.tr(this);
}
